syntax = "proto3";

package usbforwarder;
option go_package = "https://github.com/iotea-com/IoTea/libs/protocols/forwarder";

service DeviceForwarder {
    rpc CreateVirtualDevice(CreateDeviceRequest) returns (CreateDeviceResponse);
    rpc StreamDeviceData(stream DeviceData) returns (stream DeviceData);
  }
  
  message CreateDeviceRequest {
    string deviceName = 1; // The desired name/path of the virtual device
  }
  
  message CreateDeviceResponse {
    bool success = 1;
    string message = 2; // Details about success or failure
  }
  
  message DeviceData {
    bytes data = 1; // The data from/to the device
  }