// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: forwarder.proto

package forwarder

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeviceForwarder_CreateVirtualDevice_FullMethodName = "/usbforwarder.DeviceForwarder/CreateVirtualDevice"
	DeviceForwarder_StreamDeviceData_FullMethodName    = "/usbforwarder.DeviceForwarder/StreamDeviceData"
)

// DeviceForwarderClient is the client API for DeviceForwarder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceForwarderClient interface {
	CreateVirtualDevice(ctx context.Context, in *CreateDeviceRequest, opts ...grpc.CallOption) (*CreateDeviceResponse, error)
	StreamDeviceData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DeviceData, DeviceData], error)
}

type deviceForwarderClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceForwarderClient(cc grpc.ClientConnInterface) DeviceForwarderClient {
	return &deviceForwarderClient{cc}
}

func (c *deviceForwarderClient) CreateVirtualDevice(ctx context.Context, in *CreateDeviceRequest, opts ...grpc.CallOption) (*CreateDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDeviceResponse)
	err := c.cc.Invoke(ctx, DeviceForwarder_CreateVirtualDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceForwarderClient) StreamDeviceData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DeviceData, DeviceData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeviceForwarder_ServiceDesc.Streams[0], DeviceForwarder_StreamDeviceData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DeviceData, DeviceData]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceForwarder_StreamDeviceDataClient = grpc.BidiStreamingClient[DeviceData, DeviceData]

// DeviceForwarderServer is the server API for DeviceForwarder service.
// All implementations must embed UnimplementedDeviceForwarderServer
// for forward compatibility.
type DeviceForwarderServer interface {
	CreateVirtualDevice(context.Context, *CreateDeviceRequest) (*CreateDeviceResponse, error)
	StreamDeviceData(grpc.BidiStreamingServer[DeviceData, DeviceData]) error
	mustEmbedUnimplementedDeviceForwarderServer()
}

// UnimplementedDeviceForwarderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceForwarderServer struct{}

func (UnimplementedDeviceForwarderServer) CreateVirtualDevice(context.Context, *CreateDeviceRequest) (*CreateDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVirtualDevice not implemented")
}
func (UnimplementedDeviceForwarderServer) StreamDeviceData(grpc.BidiStreamingServer[DeviceData, DeviceData]) error {
	return status.Errorf(codes.Unimplemented, "method StreamDeviceData not implemented")
}
func (UnimplementedDeviceForwarderServer) mustEmbedUnimplementedDeviceForwarderServer() {}
func (UnimplementedDeviceForwarderServer) testEmbeddedByValue()                         {}

// UnsafeDeviceForwarderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceForwarderServer will
// result in compilation errors.
type UnsafeDeviceForwarderServer interface {
	mustEmbedUnimplementedDeviceForwarderServer()
}

func RegisterDeviceForwarderServer(s grpc.ServiceRegistrar, srv DeviceForwarderServer) {
	// If the following call pancis, it indicates UnimplementedDeviceForwarderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceForwarder_ServiceDesc, srv)
}

func _DeviceForwarder_CreateVirtualDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceForwarderServer).CreateVirtualDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceForwarder_CreateVirtualDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceForwarderServer).CreateVirtualDevice(ctx, req.(*CreateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceForwarder_StreamDeviceData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DeviceForwarderServer).StreamDeviceData(&grpc.GenericServerStream[DeviceData, DeviceData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceForwarder_StreamDeviceDataServer = grpc.BidiStreamingServer[DeviceData, DeviceData]

// DeviceForwarder_ServiceDesc is the grpc.ServiceDesc for DeviceForwarder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceForwarder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usbforwarder.DeviceForwarder",
	HandlerType: (*DeviceForwarderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVirtualDevice",
			Handler:    _DeviceForwarder_CreateVirtualDevice_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamDeviceData",
			Handler:       _DeviceForwarder_StreamDeviceData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "forwarder.proto",
}
