// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: dev-monitor.proto

package monitor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DevMonitorService_KeepAlive_FullMethodName       = "/devmonitor.DevMonitorService/KeepAlive"
	DevMonitorService_RestartServices_FullMethodName = "/devmonitor.DevMonitorService/RestartServices"
)

// DevMonitorServiceClient is the client API for DevMonitorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DevMonitorServiceClient interface {
	// KeepAlive is initiated by a client on connection. When the client stream closes,
	// the server will send a KeepAlive response to all the clients.
	KeepAlive(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[KeepAliveRequest, KeepAliveResponse], error)
	// Restarts all services connected to the dev monitor.
	RestartServices(ctx context.Context, in *RestartServicesRequest, opts ...grpc.CallOption) (*RestartServicesResponse, error)
}

type devMonitorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDevMonitorServiceClient(cc grpc.ClientConnInterface) DevMonitorServiceClient {
	return &devMonitorServiceClient{cc}
}

func (c *devMonitorServiceClient) KeepAlive(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[KeepAliveRequest, KeepAliveResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DevMonitorService_ServiceDesc.Streams[0], DevMonitorService_KeepAlive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[KeepAliveRequest, KeepAliveResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DevMonitorService_KeepAliveClient = grpc.BidiStreamingClient[KeepAliveRequest, KeepAliveResponse]

func (c *devMonitorServiceClient) RestartServices(ctx context.Context, in *RestartServicesRequest, opts ...grpc.CallOption) (*RestartServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestartServicesResponse)
	err := c.cc.Invoke(ctx, DevMonitorService_RestartServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DevMonitorServiceServer is the server API for DevMonitorService service.
// All implementations must embed UnimplementedDevMonitorServiceServer
// for forward compatibility.
type DevMonitorServiceServer interface {
	// KeepAlive is initiated by a client on connection. When the client stream closes,
	// the server will send a KeepAlive response to all the clients.
	KeepAlive(grpc.BidiStreamingServer[KeepAliveRequest, KeepAliveResponse]) error
	// Restarts all services connected to the dev monitor.
	RestartServices(context.Context, *RestartServicesRequest) (*RestartServicesResponse, error)
	mustEmbedUnimplementedDevMonitorServiceServer()
}

// UnimplementedDevMonitorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDevMonitorServiceServer struct{}

func (UnimplementedDevMonitorServiceServer) KeepAlive(grpc.BidiStreamingServer[KeepAliveRequest, KeepAliveResponse]) error {
	return status.Errorf(codes.Unimplemented, "method KeepAlive not implemented")
}
func (UnimplementedDevMonitorServiceServer) RestartServices(context.Context, *RestartServicesRequest) (*RestartServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartServices not implemented")
}
func (UnimplementedDevMonitorServiceServer) mustEmbedUnimplementedDevMonitorServiceServer() {}
func (UnimplementedDevMonitorServiceServer) testEmbeddedByValue()                           {}

// UnsafeDevMonitorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DevMonitorServiceServer will
// result in compilation errors.
type UnsafeDevMonitorServiceServer interface {
	mustEmbedUnimplementedDevMonitorServiceServer()
}

func RegisterDevMonitorServiceServer(s grpc.ServiceRegistrar, srv DevMonitorServiceServer) {
	// If the following call pancis, it indicates UnimplementedDevMonitorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DevMonitorService_ServiceDesc, srv)
}

func _DevMonitorService_KeepAlive_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DevMonitorServiceServer).KeepAlive(&grpc.GenericServerStream[KeepAliveRequest, KeepAliveResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DevMonitorService_KeepAliveServer = grpc.BidiStreamingServer[KeepAliveRequest, KeepAliveResponse]

func _DevMonitorService_RestartServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevMonitorServiceServer).RestartServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DevMonitorService_RestartServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevMonitorServiceServer).RestartServices(ctx, req.(*RestartServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DevMonitorService_ServiceDesc is the grpc.ServiceDesc for DevMonitorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DevMonitorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "devmonitor.DevMonitorService",
	HandlerType: (*DevMonitorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RestartServices",
			Handler:    _DevMonitorService_RestartServices_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "KeepAlive",
			Handler:       _DevMonitorService_KeepAlive_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "dev-monitor.proto",
}
