[supervisord]
user=root
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:dev-monitor]
command=air -c ./dev/.air.toml
directory=/iotea/services/dev-monitor
autostart=true
autorestart=true
stdout_logfile=/var/log/dev_monitor.log
stderr_logfile=stdout

[program:orchestrator]
command=air -c ./dev/.air.toml
directory=/iotea/services/orchestrator
autostart=true
autorestart=true
stdout_logfile=/var/log/orchestrator.log
stderr_logfile=stdout

[program:runtime]
command=air -c ./dev/.air.toml
directory=/iotea/services/runtime
autostart=true
autorestart=true
stdout_logfile=/var/log/runtime.log
stderr_logfile=stdout

[program:http-api]
command=air
directory=/iotea/services/http-api
autostart=true
autorestart=true
stdout_logfile=/var/log/http_api.log
stderr_logfile=stdout

[program:devenv]
command=air 
directory=/iotea/services/devenv
autostart=true
autorestart=true
stdout_logfile=/var/log/devenv.log
stderr_logfile=stdout
