receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  clickhouse:
    endpoint: "clickhouse://clickhouse:9000"
    username: "iotea"
    password: "iotea"
    database: "default"
    ttl: 8h
    create_schema: false

processors:
  batch:
    timeout: 1s

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ clickhouse ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ clickhouse ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ clickhouse ]
