// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO app.accounts (
  user_id, type, provider, provider_account_id,
  refresh_token, access_token, expires_at, token_type,
  scope, id_token, session_state
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, user_id, type, provider, provider_account_id, refresh_token, access_token, expires_at, token_type, scope, id_token, session_state
`

type CreateAccountParams struct {
	UserID            string  `json:"user_id"`
	Type              string  `json:"type"`
	Provider          string  `json:"provider"`
	ProviderAccountID string  `json:"provider_account_id"`
	RefreshToken      *string `json:"refresh_token"`
	AccessToken       *string `json:"access_token"`
	ExpiresAt         *int32  `json:"expires_at"`
	TokenType         *string `json:"token_type"`
	Scope             *string `json:"scope"`
	IDToken           *string `json:"id_token"`
	SessionState      *string `json:"session_state"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (AppAccount, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.Type,
		arg.Provider,
		arg.ProviderAccountID,
		arg.RefreshToken,
		arg.AccessToken,
		arg.ExpiresAt,
		arg.TokenType,
		arg.Scope,
		arg.IDToken,
		arg.SessionState,
	)
	var i AppAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Provider,
		&i.ProviderAccountID,
		&i.RefreshToken,
		&i.AccessToken,
		&i.ExpiresAt,
		&i.TokenType,
		&i.Scope,
		&i.IDToken,
		&i.SessionState,
	)
	return i, err
}

const createAuthToken = `-- name: CreateAuthToken :one
INSERT INTO app.auth_tokens (
  user_id, token, type, expires_at
) VALUES (
  $1, $2, $3, $4
)
RETURNING user_id, token, type, expires_at, created_at
`

func (q *Queries) CreateAuthToken(ctx context.Context, userID string, token string, type_ AppAuthTokenType, expiresAt time.Time) (AppAuthToken, error) {
	row := q.db.QueryRow(ctx, createAuthToken,
		userID,
		token,
		type_,
		expiresAt,
	)
	var i AppAuthToken
	err := row.Scan(
		&i.UserID,
		&i.Token,
		&i.Type,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO app.sessions (
  session_token, user_id, expires
) VALUES (
  $1, $2, $3
)
RETURNING id, session_token, user_id, expires
`

func (q *Queries) CreateSession(ctx context.Context, sessionToken string, userID string, expires time.Time) (AppSession, error) {
	row := q.db.QueryRow(ctx, createSession, sessionToken, userID, expires)
	var i AppSession
	err := row.Scan(
		&i.ID,
		&i.SessionToken,
		&i.UserID,
		&i.Expires,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM app.accounts
WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const deleteAuthToken = `-- name: DeleteAuthToken :exec
DELETE FROM app.auth_tokens
WHERE token = $1
`

func (q *Queries) DeleteAuthToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteAuthToken, token)
	return err
}

const deleteAuthTokensByUser = `-- name: DeleteAuthTokensByUser :exec
DELETE FROM app.auth_tokens
WHERE user_id = $1 AND type = $2
`

func (q *Queries) DeleteAuthTokensByUser(ctx context.Context, userID string, type_ AppAuthTokenType) error {
	_, err := q.db.Exec(ctx, deleteAuthTokensByUser, userID, type_)
	return err
}

const deleteExpiredAuthTokens = `-- name: DeleteExpiredAuthTokens :exec
DELETE FROM app.auth_tokens
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredAuthTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAuthTokens)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM app.sessions
WHERE expires < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM app.sessions
WHERE session_token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, sessionToken string) error {
	_, err := q.db.Exec(ctx, deleteSession, sessionToken)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, user_id, type, provider, provider_account_id, refresh_token, access_token, expires_at, token_type, scope, id_token, session_state FROM app.accounts
WHERE provider = $1 AND provider_account_id = $2
`

func (q *Queries) GetAccount(ctx context.Context, provider string, providerAccountID string) (AppAccount, error) {
	row := q.db.QueryRow(ctx, getAccount, provider, providerAccountID)
	var i AppAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Provider,
		&i.ProviderAccountID,
		&i.RefreshToken,
		&i.AccessToken,
		&i.ExpiresAt,
		&i.TokenType,
		&i.Scope,
		&i.IDToken,
		&i.SessionState,
	)
	return i, err
}

const getAccountsByUser = `-- name: GetAccountsByUser :many
SELECT id, user_id, type, provider, provider_account_id, refresh_token, access_token, expires_at, token_type, scope, id_token, session_state FROM app.accounts
WHERE user_id = $1
`

func (q *Queries) GetAccountsByUser(ctx context.Context, userID string) ([]AppAccount, error) {
	rows, err := q.db.Query(ctx, getAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppAccount{}
	for rows.Next() {
		var i AppAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Provider,
			&i.ProviderAccountID,
			&i.RefreshToken,
			&i.AccessToken,
			&i.ExpiresAt,
			&i.TokenType,
			&i.Scope,
			&i.IDToken,
			&i.SessionState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthToken = `-- name: GetAuthToken :one
SELECT user_id, token, type, expires_at, created_at FROM app.auth_tokens
WHERE token = $1 AND expires_at > NOW()
`

func (q *Queries) GetAuthToken(ctx context.Context, token string) (AppAuthToken, error) {
	row := q.db.QueryRow(ctx, getAuthToken, token)
	var i AppAuthToken
	err := row.Scan(
		&i.UserID,
		&i.Token,
		&i.Type,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthTokenWithUser = `-- name: GetAuthTokenWithUser :one
SELECT
  at.user_id,
  at.token,
  at.type,
  at.expires_at,
  at.created_at,
  u.id AS joined_user_id,
  u.name AS joined_user_name,
  u.email AS joined_user_email,
  u.email_verified AS joined_user_email_verified,
  u.password AS joined_user_password,
  u.image AS joined_user_image
FROM app.auth_tokens at
JOIN app.users u ON at.user_id = u.id
WHERE at.token = $1
LIMIT 1
`

type GetAuthTokenWithUserRow struct {
	UserID                  string             `json:"user_id"`
	Token                   string             `json:"token"`
	Type                    AppAuthTokenType   `json:"type"`
	ExpiresAt               time.Time          `json:"expires_at"`
	CreatedAt               time.Time          `json:"created_at"`
	JoinedUserID            string             `json:"joined_user_id"`
	JoinedUserName          *string            `json:"joined_user_name"`
	JoinedUserEmail         *string            `json:"joined_user_email"`
	JoinedUserEmailVerified pgtype.Timestamptz `json:"joined_user_email_verified"`
	JoinedUserPassword      *string            `json:"joined_user_password"`
	JoinedUserImage         *string            `json:"joined_user_image"`
}

func (q *Queries) GetAuthTokenWithUser(ctx context.Context, token string) (GetAuthTokenWithUserRow, error) {
	row := q.db.QueryRow(ctx, getAuthTokenWithUser, token)
	var i GetAuthTokenWithUserRow
	err := row.Scan(
		&i.UserID,
		&i.Token,
		&i.Type,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.JoinedUserID,
		&i.JoinedUserName,
		&i.JoinedUserEmail,
		&i.JoinedUserEmailVerified,
		&i.JoinedUserPassword,
		&i.JoinedUserImage,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, session_token, user_id, expires FROM app.sessions
WHERE session_token = $1
`

func (q *Queries) GetSession(ctx context.Context, sessionToken string) (AppSession, error) {
	row := q.db.QueryRow(ctx, getSession, sessionToken)
	var i AppSession
	err := row.Scan(
		&i.ID,
		&i.SessionToken,
		&i.UserID,
		&i.Expires,
	)
	return i, err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT 
  s.id, s.session_token, s.user_id, s.expires,
  u.id as user_id,
  u.name as user_name,
  u.email as user_email,
  u.image as user_image
FROM app.sessions s
JOIN app.users u ON s.user_id = u.id
WHERE s.session_token = $1 AND s.expires > NOW()
`

type GetSessionWithUserRow struct {
	ID           string    `json:"id"`
	SessionToken string    `json:"session_token"`
	UserID       string    `json:"user_id"`
	Expires      time.Time `json:"expires"`
	UserID_2     string    `json:"user_id_2"`
	UserName     *string   `json:"user_name"`
	UserEmail    *string   `json:"user_email"`
	UserImage    *string   `json:"user_image"`
}

func (q *Queries) GetSessionWithUser(ctx context.Context, sessionToken string) (GetSessionWithUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUser, sessionToken)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.ID,
		&i.SessionToken,
		&i.UserID,
		&i.Expires,
		&i.UserID_2,
		&i.UserName,
		&i.UserEmail,
		&i.UserImage,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :one
UPDATE app.sessions
SET expires = $2
WHERE session_token = $1
RETURNING id, session_token, user_id, expires
`

func (q *Queries) UpdateSession(ctx context.Context, sessionToken string, expires time.Time) (AppSession, error) {
	row := q.db.QueryRow(ctx, updateSession, sessionToken, expires)
	var i AppSession
	err := row.Scan(
		&i.ID,
		&i.SessionToken,
		&i.UserID,
		&i.Expires,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE app.users
SET password = $2
WHERE id = $1
RETURNING id, name, email, email_verified, password, image
`

func (q *Queries) UpdateUserPassword(ctx context.Context, iD string, password *string) (AppUser, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, iD, password)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Password,
		&i.Image,
	)
	return i, err
}
