// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package db

import (
	"context"
)

const countChannelsFiltered = `-- name: CountChannelsFiltered :one
SELECT COUNT(*) FROM app.channels c
WHERE c.space_id = $1
  AND ($2::text = '' OR c.id ILIKE '%' || $2 || '%' OR c.name ILIKE '%' || $2 || '%')
  AND (
    cardinality($3::text[]) = 0
    OR c.id IN (
      SELECT DISTINCT at.channel_id
      FROM app.applied_tags at
      WHERE at.tag_id = ANY($3::text[])
    )
  )
`

func (q *Queries) CountChannelsFiltered(ctx context.Context, spaceID string, column2 string, column3 []string) (int64, error) {
	row := q.db.QueryRow(ctx, countChannelsFiltered, spaceID, column2, column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO app.channels (
  id, name, space_id, config, created_by, updated_by
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, name, space_id, config, created_at, created_by, updated_at, updated_by, published_at, published_by
`

type CreateChannelParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	SpaceID   string `json:"space_id"`
	Config    []byte `json:"config"`
	CreatedBy string `json:"created_by"`
	UpdatedBy string `json:"updated_by"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (AppChannel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.ID,
		arg.Name,
		arg.SpaceID,
		arg.Config,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i AppChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SpaceID,
		&i.Config,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.PublishedAt,
		&i.PublishedBy,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM app.channels
WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteChannel, id)
	return err
}

const deleteChannelsBySpace = `-- name: DeleteChannelsBySpace :exec
DELETE FROM app.channels
WHERE space_id = $1
`

func (q *Queries) DeleteChannelsBySpace(ctx context.Context, spaceID string) error {
	_, err := q.db.Exec(ctx, deleteChannelsBySpace, spaceID)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT id, name, space_id, config, created_at, created_by, updated_at, updated_by, published_at, published_by FROM app.channels
WHERE id = $1
`

func (q *Queries) GetChannel(ctx context.Context, id string) (AppChannel, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i AppChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SpaceID,
		&i.Config,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.PublishedAt,
		&i.PublishedBy,
	)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT id, name, space_id, config, created_at, created_by, updated_at, updated_by, published_at, published_by FROM app.channels
WHERE space_id = $1
ORDER BY name
`

func (q *Queries) ListChannels(ctx context.Context, spaceID string) ([]AppChannel, error) {
	rows, err := q.db.Query(ctx, listChannels, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppChannel{}
	for rows.Next() {
		var i AppChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SpaceID,
			&i.Config,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.PublishedAt,
			&i.PublishedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsFiltered = `-- name: ListChannelsFiltered :many
SELECT id, name, space_id, config, created_at, created_by, updated_at, updated_by, published_at, published_by FROM app.channels c
WHERE c.space_id = $1
  AND ($2::text = '' OR c.id ILIKE '%' || $2 || '%' OR c.name ILIKE '%' || $2 || '%')
  AND (
    cardinality($3::text[]) = 0
    OR c.id IN (
      SELECT DISTINCT at.channel_id
      FROM app.applied_tags at
      WHERE at.tag_id = ANY($3::text[])
    )
  )
ORDER BY c.updated_at DESC
LIMIT $4 OFFSET $5
`

func (q *Queries) ListChannelsFiltered(ctx context.Context, spaceID string, column2 string, column3 []string, limit int32, offset int32) ([]AppChannel, error) {
	rows, err := q.db.Query(ctx, listChannelsFiltered,
		spaceID,
		column2,
		column3,
		limit,
		offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppChannel{}
	for rows.Next() {
		var i AppChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SpaceID,
			&i.Config,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.PublishedAt,
			&i.PublishedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedChannels = `-- name: ListPublishedChannels :many
SELECT id, name, space_id, config, created_at, created_by, updated_at, updated_by, published_at, published_by FROM app.channels
WHERE space_id = $1 AND published_at IS NOT NULL
ORDER BY published_at DESC
`

func (q *Queries) ListPublishedChannels(ctx context.Context, spaceID string) ([]AppChannel, error) {
	rows, err := q.db.Query(ctx, listPublishedChannels, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppChannel{}
	for rows.Next() {
		var i AppChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SpaceID,
			&i.Config,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.PublishedAt,
			&i.PublishedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishChannel = `-- name: PublishChannel :one
UPDATE app.channels
SET published_at = NOW(),
    published_by = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, space_id, config, created_at, created_by, updated_at, updated_by, published_at, published_by
`

func (q *Queries) PublishChannel(ctx context.Context, iD string, publishedBy *string) (AppChannel, error) {
	row := q.db.QueryRow(ctx, publishChannel, iD, publishedBy)
	var i AppChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SpaceID,
		&i.Config,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.PublishedAt,
		&i.PublishedBy,
	)
	return i, err
}

const unpublishChannel = `-- name: UnpublishChannel :one
UPDATE app.channels
SET published_at = NULL,
    published_by = NULL,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, space_id, config, created_at, created_by, updated_at, updated_by, published_at, published_by
`

func (q *Queries) UnpublishChannel(ctx context.Context, id string) (AppChannel, error) {
	row := q.db.QueryRow(ctx, unpublishChannel, id)
	var i AppChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SpaceID,
		&i.Config,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.PublishedAt,
		&i.PublishedBy,
	)
	return i, err
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE app.channels
SET name = $2,
    config = $3,
    updated_by = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, space_id, config, created_at, created_by, updated_at, updated_by, published_at, published_by
`

func (q *Queries) UpdateChannel(ctx context.Context, iD string, name string, config []byte, updatedBy string) (AppChannel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		iD,
		name,
		config,
		updatedBy,
	)
	var i AppChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SpaceID,
		&i.Config,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.PublishedAt,
		&i.PublishedBy,
	)
	return i, err
}

const updateChannelConfig = `-- name: UpdateChannelConfig :one
UPDATE app.channels
SET config = $2,
    updated_by = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, space_id, config, created_at, created_by, updated_at, updated_by, published_at, published_by
`

func (q *Queries) UpdateChannelConfig(ctx context.Context, iD string, config []byte, updatedBy string) (AppChannel, error) {
	row := q.db.QueryRow(ctx, updateChannelConfig, iD, config, updatedBy)
	var i AppChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SpaceID,
		&i.Config,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.PublishedAt,
		&i.PublishedBy,
	)
	return i, err
}
