// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: models.sql

package db

import (
	"context"
)

const countModelsFiltered = `-- name: CountModelsFiltered :one
SELECT COUNT(*) FROM app.models m
WHERE m.space_id = $1
  AND ($2::text = '' OR m.id ILIKE '%' || $2 || '%' OR m.name ILIKE '%' || $2 || '%')
  AND (
    cardinality($3::text[]) = 0
    OR m.id IN (
      SELECT DISTINCT at.model_id
      FROM app.applied_tags at
      WHERE at.tag_id = ANY($3::text[])
    )
  )
`

func (q *Queries) CountModelsFiltered(ctx context.Context, spaceID string, column2 string, column3 []string) (int64, error) {
	row := q.db.QueryRow(ctx, countModelsFiltered, spaceID, column2, column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createModel = `-- name: CreateModel :one
INSERT INTO app.models (
  id, space_id, name, attributes, created_by, updated_by
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, space_id, name, attributes, created_at, updated_at, created_by, updated_by
`

type CreateModelParams struct {
	ID         string `json:"id"`
	SpaceID    string `json:"space_id"`
	Name       string `json:"name"`
	Attributes []byte `json:"attributes"`
	CreatedBy  string `json:"created_by"`
	UpdatedBy  string `json:"updated_by"`
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) (AppModel, error) {
	row := q.db.QueryRow(ctx, createModel,
		arg.ID,
		arg.SpaceID,
		arg.Name,
		arg.Attributes,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i AppModel
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteModel = `-- name: DeleteModel :exec
DELETE FROM app.models
WHERE id = $1
`

func (q *Queries) DeleteModel(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteModel, id)
	return err
}

const deleteModelsBySpace = `-- name: DeleteModelsBySpace :exec
DELETE FROM app.models
WHERE space_id = $1
`

func (q *Queries) DeleteModelsBySpace(ctx context.Context, spaceID string) error {
	_, err := q.db.Exec(ctx, deleteModelsBySpace, spaceID)
	return err
}

const getModel = `-- name: GetModel :one
SELECT id, space_id, name, attributes, created_at, updated_at, created_by, updated_by FROM app.models
WHERE id = $1
`

func (q *Queries) GetModel(ctx context.Context, id string) (AppModel, error) {
	row := q.db.QueryRow(ctx, getModel, id)
	var i AppModel
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listModels = `-- name: ListModels :many
SELECT id, space_id, name, attributes, created_at, updated_at, created_by, updated_by FROM app.models
WHERE space_id = $1
ORDER BY name
`

func (q *Queries) ListModels(ctx context.Context, spaceID string) ([]AppModel, error) {
	rows, err := q.db.Query(ctx, listModels, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppModel{}
	for rows.Next() {
		var i AppModel
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.Name,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelsFiltered = `-- name: ListModelsFiltered :many
SELECT id, space_id, name, attributes, created_at, updated_at, created_by, updated_by FROM app.models m
WHERE m.space_id = $1
  AND ($2::text = '' OR m.id ILIKE '%' || $2 || '%' OR m.name ILIKE '%' || $2 || '%')
  AND (
    cardinality($3::text[]) = 0
    OR m.id IN (
      SELECT DISTINCT at.model_id
      FROM app.applied_tags at
      WHERE at.tag_id = ANY($3::text[])
    )
  )
ORDER BY m.updated_at DESC
LIMIT $4 OFFSET $5
`

func (q *Queries) ListModelsFiltered(ctx context.Context, spaceID string, column2 string, column3 []string, limit int32, offset int32) ([]AppModel, error) {
	rows, err := q.db.Query(ctx, listModelsFiltered,
		spaceID,
		column2,
		column3,
		limit,
		offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppModel{}
	for rows.Next() {
		var i AppModel
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.Name,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModel = `-- name: UpdateModel :one
UPDATE app.models
SET name = $2,
    attributes = $3,
    updated_by = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, space_id, name, attributes, created_at, updated_at, created_by, updated_by
`

func (q *Queries) UpdateModel(ctx context.Context, iD string, name string, attributes []byte, updatedBy string) (AppModel, error) {
	row := q.db.QueryRow(ctx, updateModel,
		iD,
		name,
		attributes,
		updatedBy,
	)
	var i AppModel
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
