// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppAuthTokenType string

const (
	AppAuthTokenTypeEMAILVERIFICATION AppAuthTokenType = "EMAIL_VERIFICATION"
	AppAuthTokenTypeMAGICLINK         AppAuthTokenType = "MAGIC_LINK"
	AppAuthTokenTypeREFRESH           AppAuthTokenType = "REFRESH"
)

func (e *AppAuthTokenType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppAuthTokenType(s)
	case string:
		*e = AppAuthTokenType(s)
	default:
		return fmt.Errorf("unsupported scan type for AppAuthTokenType: %T", src)
	}
	return nil
}

type NullAppAuthTokenType struct {
	AppAuthTokenType AppAuthTokenType `json:"app_AuthTokenType"`
	Valid            bool             `json:"valid"` // Valid is true if AppAuthTokenType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppAuthTokenType) Scan(value interface{}) error {
	if value == nil {
		ns.AppAuthTokenType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppAuthTokenType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppAuthTokenType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppAuthTokenType), nil
}

type AppOrganizationRole string

const (
	AppOrganizationRoleMEMBER AppOrganizationRole = "MEMBER"
	AppOrganizationRoleADMIN  AppOrganizationRole = "ADMIN"
)

func (e *AppOrganizationRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppOrganizationRole(s)
	case string:
		*e = AppOrganizationRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AppOrganizationRole: %T", src)
	}
	return nil
}

type NullAppOrganizationRole struct {
	AppOrganizationRole AppOrganizationRole `json:"app_OrganizationRole"`
	Valid               bool                `json:"valid"` // Valid is true if AppOrganizationRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppOrganizationRole) Scan(value interface{}) error {
	if value == nil {
		ns.AppOrganizationRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppOrganizationRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppOrganizationRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppOrganizationRole), nil
}

type AppUserOnSpaceRole string

const (
	AppUserOnSpaceRoleMEMBER AppUserOnSpaceRole = "MEMBER"
	AppUserOnSpaceRoleOWNER  AppUserOnSpaceRole = "OWNER"
)

func (e *AppUserOnSpaceRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppUserOnSpaceRole(s)
	case string:
		*e = AppUserOnSpaceRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AppUserOnSpaceRole: %T", src)
	}
	return nil
}

type NullAppUserOnSpaceRole struct {
	AppUserOnSpaceRole AppUserOnSpaceRole `json:"app_UserOnSpaceRole"`
	Valid              bool               `json:"valid"` // Valid is true if AppUserOnSpaceRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppUserOnSpaceRole) Scan(value interface{}) error {
	if value == nil {
		ns.AppUserOnSpaceRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppUserOnSpaceRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppUserOnSpaceRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppUserOnSpaceRole), nil
}

type AppAccount struct {
	ID                string  `json:"id"`
	UserID            string  `json:"user_id"`
	Type              string  `json:"type"`
	Provider          string  `json:"provider"`
	ProviderAccountID string  `json:"provider_account_id"`
	RefreshToken      *string `json:"refresh_token"`
	AccessToken       *string `json:"access_token"`
	ExpiresAt         *int32  `json:"expires_at"`
	TokenType         *string `json:"token_type"`
	Scope             *string `json:"scope"`
	IDToken           *string `json:"id_token"`
	SessionState      *string `json:"session_state"`
}

type AppApiKey struct {
	ID                          string             `json:"id"`
	OrganizationID              string             `json:"organization_id"`
	OrganizationPermissionSetID *string            `json:"organization_permission_set_id"`
	SpaceID                     *string            `json:"space_id"`
	SpacePermissionSetID        *string            `json:"space_permission_set_id"`
	Name                        *string            `json:"name"`
	CreatedAt                   time.Time          `json:"created_at"`
	CreatedBy                   string             `json:"created_by"`
	ExpiresAt                   pgtype.Timestamptz `json:"expires_at"`
}

type AppAppliedTag struct {
	ID        string    `json:"id"`
	SpaceID   string    `json:"space_id"`
	TagID     string    `json:"tag_id"`
	ChannelID *string   `json:"channel_id"`
	ModelID   *string   `json:"model_id"`
	ThingID   *string   `json:"thing_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	CreatedBy string    `json:"created_by"`
	UpdatedBy string    `json:"updated_by"`
}

type AppAuthToken struct {
	UserID    string           `json:"user_id"`
	Token     string           `json:"token"`
	Type      AppAuthTokenType `json:"type"`
	ExpiresAt time.Time        `json:"expires_at"`
	CreatedAt time.Time        `json:"created_at"`
}

type AppCertificate struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	SpaceID string `json:"space_id"`
	Policy  []byte `json:"policy"`
	Revoke  bool   `json:"revoke"`
}

type AppChannel struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	SpaceID     string             `json:"space_id"`
	Config      []byte             `json:"config"`
	CreatedAt   time.Time          `json:"created_at"`
	CreatedBy   string             `json:"created_by"`
	UpdatedAt   time.Time          `json:"updated_at"`
	UpdatedBy   string             `json:"updated_by"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	PublishedBy *string            `json:"published_by"`
}

type AppEnvironment struct {
	ID              int32     `json:"id"`
	EnvironmentID   string    `json:"environment_id"`
	EnvironmentName string    `json:"environment_name"`
	Region          string    `json:"region"`
	State           string    `json:"state"`
	PublicDns       string    `json:"public_dns"`
	SshKeyName      string    `json:"ssh_key_name"`
	CreatedAt       time.Time `json:"created_at"`
	SpaceID         string    `json:"space_id"`
}

type AppMemberSpacePermission struct {
	ID                   string    `json:"id"`
	OrganizationMemberID string    `json:"organization_member_id"`
	PermissionSetID      string    `json:"permission_set_id"`
	CreatedAt            time.Time `json:"created_at"`
}

type AppModel struct {
	ID         string    `json:"id"`
	SpaceID    string    `json:"space_id"`
	Name       string    `json:"name"`
	Attributes []byte    `json:"attributes"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	CreatedBy  string    `json:"created_by"`
	UpdatedBy  string    `json:"updated_by"`
}

type AppOrganization struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	CreatedBy string    `json:"created_by"`
	UpdatedAt time.Time `json:"updated_at"`
	UpdatedBy string    `json:"updated_by"`
}

type AppOrganizationMember struct {
	ID                          string              `json:"id"`
	OrganizationID              string              `json:"organization_id"`
	UserID                      string              `json:"user_id"`
	Role                        AppOrganizationRole `json:"role"`
	OrganizationPermissionSetID string              `json:"organization_permission_set_id"`
	CreatedAt                   time.Time           `json:"created_at"`
	UpdatedAt                   time.Time           `json:"updated_at"`
}

type AppPermission struct {
	ID             string    `json:"id"`
	OrganizationID string    `json:"organization_id"`
	SpaceID        *string   `json:"space_id"`
	Name           string    `json:"name"`
	Permissions    []string  `json:"permissions"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	CreatedBy      string    `json:"created_by"`
	UpdatedBy      string    `json:"updated_by"`
}

type AppSession struct {
	ID           string    `json:"id"`
	SessionToken string    `json:"session_token"`
	UserID       string    `json:"user_id"`
	Expires      time.Time `json:"expires"`
}

type AppSpace struct {
	ID             string    `json:"id"`
	OrganizationID string    `json:"organization_id"`
	Name           string    `json:"name"`
	CreatedAt      time.Time `json:"created_at"`
	CreatedBy      string    `json:"created_by"`
	UpdatedAt      time.Time `json:"updated_at"`
	UpdatedBy      string    `json:"updated_by"`
}

type AppTag struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	SpaceID   string    `json:"space_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	CreatedBy string    `json:"created_by"`
	UpdatedBy string    `json:"updated_by"`
}

type AppThing struct {
	ID            string    `json:"id"`
	Name          string    `json:"name"`
	SpaceID       string    `json:"space_id"`
	Attributes    []byte    `json:"attributes"`
	Internal      bool      `json:"internal"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	CreatedBy     string    `json:"created_by"`
	UpdatedBy     string    `json:"updated_by"`
	ThingCategory string    `json:"thing_category"`
}

type AppUser struct {
	ID            string             `json:"id"`
	Name          *string            `json:"name"`
	Email         *string            `json:"email"`
	EmailVerified pgtype.Timestamptz `json:"email_verified"`
	Password      *string            `json:"password"`
	Image         *string            `json:"image"`
}
