// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package db

import (
	"context"
	"time"
)

const countOrganizationAdmins = `-- name: CountOrganizationAdmins :one
SELECT COUNT(*)
FROM app.organization_members
WHERE organization_id = $1 AND role = 'ADMIN'
`

func (q *Queries) CountOrganizationAdmins(ctx context.Context, organizationID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationAdmins, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrganizationMembersWithFilter = `-- name: CountOrganizationMembersWithFilter :one
SELECT COUNT(*)
FROM app.organization_members om
JOIN app.users u ON u.id = om.user_id
WHERE om.organization_id = $1
  AND ($2 = '' OR LOWER(u.email) LIKE LOWER('%' || $2 || '%'))
`

func (q *Queries) CountOrganizationMembersWithFilter(ctx context.Context, organizationID string, column2 interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationMembersWithFilter, organizationID, column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO app.organizations (
  id, name, created_by, updated_by
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, name, created_at, created_by, updated_at, updated_by
`

func (q *Queries) CreateOrganization(ctx context.Context, iD string, name string, createdBy string, updatedBy string) (AppOrganization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		iD,
		name,
		createdBy,
		updatedBy,
	)
	var i AppOrganization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const createOrganizationMember = `-- name: CreateOrganizationMember :one
INSERT INTO app.organization_members (
  organization_id, user_id, role, organization_permission_set_id
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, organization_id, user_id, role, organization_permission_set_id, created_at, updated_at
`

func (q *Queries) CreateOrganizationMember(ctx context.Context, organizationID string, userID string, role AppOrganizationRole, organizationPermissionSetID string) (AppOrganizationMember, error) {
	row := q.db.QueryRow(ctx, createOrganizationMember,
		organizationID,
		userID,
		role,
		organizationPermissionSetID,
	)
	var i AppOrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.OrganizationPermissionSetID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM app.organizations
WHERE id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteOrganization, id)
	return err
}

const deleteOrganizationApiKeys = `-- name: DeleteOrganizationApiKeys :exec
DELETE FROM app."apiKeys"
WHERE organization_id = $1
`

func (q *Queries) DeleteOrganizationApiKeys(ctx context.Context, organizationID string) error {
	_, err := q.db.Exec(ctx, deleteOrganizationApiKeys, organizationID)
	return err
}

const deleteOrganizationMember = `-- name: DeleteOrganizationMember :exec
DELETE FROM app.organization_members
WHERE id = $1
`

func (q *Queries) DeleteOrganizationMember(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteOrganizationMember, id)
	return err
}

const deleteOrganizationMemberByOrgAndUser = `-- name: DeleteOrganizationMemberByOrgAndUser :exec
DELETE FROM app.organization_members
WHERE organization_id = $1 AND user_id = $2
`

func (q *Queries) DeleteOrganizationMemberByOrgAndUser(ctx context.Context, organizationID string, userID string) error {
	_, err := q.db.Exec(ctx, deleteOrganizationMemberByOrgAndUser, organizationID, userID)
	return err
}

const deleteOrganizationMembers = `-- name: DeleteOrganizationMembers :exec
DELETE FROM app.organization_members
WHERE organization_id = $1
`

func (q *Queries) DeleteOrganizationMembers(ctx context.Context, organizationID string) error {
	_, err := q.db.Exec(ctx, deleteOrganizationMembers, organizationID)
	return err
}

const deleteOrganizationPermissionSets = `-- name: DeleteOrganizationPermissionSets :exec
DELETE FROM app.permissions
WHERE organization_id = $1
`

func (q *Queries) DeleteOrganizationPermissionSets(ctx context.Context, organizationID string) error {
	_, err := q.db.Exec(ctx, deleteOrganizationPermissionSets, organizationID)
	return err
}

const getDefaultOrganizationPermissionSet = `-- name: GetDefaultOrganizationPermissionSet :one
SELECT id, organization_id, space_id, name, permissions, created_at, updated_at, created_by, updated_by
FROM app.permissions
WHERE organization_id = $1
  AND space_id IS NULL
  AND name = 'Default'
LIMIT 1
`

func (q *Queries) GetDefaultOrganizationPermissionSet(ctx context.Context, organizationID string) (AppPermission, error) {
	row := q.db.QueryRow(ctx, getDefaultOrganizationPermissionSet, organizationID)
	var i AppPermission
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SpaceID,
		&i.Name,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, created_at, created_by, updated_at, updated_by FROM app.organizations
WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id string) (AppOrganization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i AppOrganization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getOrganizationMember = `-- name: GetOrganizationMember :one
SELECT id, organization_id, user_id, role, organization_permission_set_id, created_at, updated_at FROM app.organization_members
WHERE organization_id = $1 AND user_id = $2
`

func (q *Queries) GetOrganizationMember(ctx context.Context, organizationID string, userID string) (AppOrganizationMember, error) {
	row := q.db.QueryRow(ctx, getOrganizationMember, organizationID, userID)
	var i AppOrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.OrganizationPermissionSetID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizationMembers = `-- name: ListOrganizationMembers :many
SELECT 
  om.id, om.organization_id, om.user_id, om.role, om.organization_permission_set_id, om.created_at, om.updated_at,
  u.name as user_name,
  u.email as user_email
FROM app.organization_members om
JOIN app.users u ON om.user_id = u.id
WHERE om.organization_id = $1
ORDER BY om.created_at DESC
`

type ListOrganizationMembersRow struct {
	ID                          string              `json:"id"`
	OrganizationID              string              `json:"organization_id"`
	UserID                      string              `json:"user_id"`
	Role                        AppOrganizationRole `json:"role"`
	OrganizationPermissionSetID string              `json:"organization_permission_set_id"`
	CreatedAt                   time.Time           `json:"created_at"`
	UpdatedAt                   time.Time           `json:"updated_at"`
	UserName                    *string             `json:"user_name"`
	UserEmail                   *string             `json:"user_email"`
}

func (q *Queries) ListOrganizationMembers(ctx context.Context, organizationID string) ([]ListOrganizationMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationMembersRow{}
	for rows.Next() {
		var i ListOrganizationMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.OrganizationPermissionSetID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationMembersWithFilter = `-- name: ListOrganizationMembersWithFilter :many
SELECT
  om.id, om.organization_id, om.user_id, om.role, om.organization_permission_set_id, om.created_at, om.updated_at,
  u.id as user_id,
  u.name as user_name,
  u.email as user_email
FROM app.organization_members om
JOIN app.users u ON u.id = om.user_id
WHERE om.organization_id = $1
  AND ($2 = '' OR LOWER(u.email) LIKE LOWER('%' || $2 || '%'))
ORDER BY om.created_at DESC
LIMIT $3 OFFSET $4
`

type ListOrganizationMembersWithFilterRow struct {
	ID                          string              `json:"id"`
	OrganizationID              string              `json:"organization_id"`
	UserID                      string              `json:"user_id"`
	Role                        AppOrganizationRole `json:"role"`
	OrganizationPermissionSetID string              `json:"organization_permission_set_id"`
	CreatedAt                   time.Time           `json:"created_at"`
	UpdatedAt                   time.Time           `json:"updated_at"`
	UserID_2                    string              `json:"user_id_2"`
	UserName                    *string             `json:"user_name"`
	UserEmail                   *string             `json:"user_email"`
}

func (q *Queries) ListOrganizationMembersWithFilter(ctx context.Context, organizationID string, column2 interface{}, limit int32, offset int32) ([]ListOrganizationMembersWithFilterRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembersWithFilter,
		organizationID,
		column2,
		limit,
		offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationMembersWithFilterRow{}
	for rows.Next() {
		var i ListOrganizationMembersWithFilterRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.OrganizationPermissionSetID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID_2,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, created_at, created_by, updated_at, updated_by FROM app.organizations
ORDER BY name
`

func (q *Queries) ListOrganizations(ctx context.Context) ([]AppOrganization, error) {
	rows, err := q.db.Query(ctx, listOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppOrganization{}
	for rows.Next() {
		var i AppOrganization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrganizationMembers = `-- name: ListUserOrganizationMembers :many
SELECT
  om.id,
  om.organization_id,
  om.user_id,
  om.role,
  om.organization_permission_set_id,
  om.created_at,
  om.updated_at,
  o.name as organization_name,
  o.created_at as organization_created_at,
  o.created_by as organization_created_by,
  o.updated_at as organization_updated_at,
  o.updated_by as organization_updated_by
FROM app.organization_members om
JOIN app.organizations o ON om.organization_id = o.id
WHERE om.user_id = $1
ORDER BY o.name
`

type ListUserOrganizationMembersRow struct {
	ID                          string              `json:"id"`
	OrganizationID              string              `json:"organization_id"`
	UserID                      string              `json:"user_id"`
	Role                        AppOrganizationRole `json:"role"`
	OrganizationPermissionSetID string              `json:"organization_permission_set_id"`
	CreatedAt                   time.Time           `json:"created_at"`
	UpdatedAt                   time.Time           `json:"updated_at"`
	OrganizationName            string              `json:"organization_name"`
	OrganizationCreatedAt       time.Time           `json:"organization_created_at"`
	OrganizationCreatedBy       string              `json:"organization_created_by"`
	OrganizationUpdatedAt       time.Time           `json:"organization_updated_at"`
	OrganizationUpdatedBy       string              `json:"organization_updated_by"`
}

func (q *Queries) ListUserOrganizationMembers(ctx context.Context, userID string) ([]ListUserOrganizationMembersRow, error) {
	rows, err := q.db.Query(ctx, listUserOrganizationMembers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserOrganizationMembersRow{}
	for rows.Next() {
		var i ListUserOrganizationMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.OrganizationPermissionSetID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationName,
			&i.OrganizationCreatedAt,
			&i.OrganizationCreatedBy,
			&i.OrganizationUpdatedAt,
			&i.OrganizationUpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE app.organizations
SET name = $2,
    updated_by = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, created_at, created_by, updated_at, updated_by
`

func (q *Queries) UpdateOrganization(ctx context.Context, iD string, name string, updatedBy string) (AppOrganization, error) {
	row := q.db.QueryRow(ctx, updateOrganization, iD, name, updatedBy)
	var i AppOrganization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateOrganizationMemberRole = `-- name: UpdateOrganizationMemberRole :one
UPDATE app.organization_members
SET role = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, user_id, role, organization_permission_set_id, created_at, updated_at
`

func (q *Queries) UpdateOrganizationMemberRole(ctx context.Context, iD string, role AppOrganizationRole) (AppOrganizationMember, error) {
	row := q.db.QueryRow(ctx, updateOrganizationMemberRole, iD, role)
	var i AppOrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.OrganizationPermissionSetID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationMemberRoleByOrgAndUser = `-- name: UpdateOrganizationMemberRoleByOrgAndUser :one
UPDATE app.organization_members
SET role = $3,
    updated_at = NOW()
WHERE organization_id = $1 AND user_id = $2
RETURNING id, organization_id, user_id, role, organization_permission_set_id, created_at, updated_at
`

func (q *Queries) UpdateOrganizationMemberRoleByOrgAndUser(ctx context.Context, organizationID string, userID string, role AppOrganizationRole) (AppOrganizationMember, error) {
	row := q.db.QueryRow(ctx, updateOrganizationMemberRoleByOrgAndUser, organizationID, userID, role)
	var i AppOrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.OrganizationPermissionSetID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
