// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrganizationApiKeys = `-- name: CountOrganizationApiKeys :one
SELECT COUNT(*) FROM app."apiKeys"
WHERE organization_id = $1
  AND space_id IS NULL
`

func (q *Queries) CountOrganizationApiKeys(ctx context.Context, organizationID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationApiKeys, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrganizationPermissionSets = `-- name: CountOrganizationPermissionSets :one
SELECT COUNT(*) FROM app.permissions
WHERE organization_id = $1
  AND space_id IS NULL
`

func (q *Queries) CountOrganizationPermissionSets(ctx context.Context, organizationID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationPermissionSets, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSpaceApiKeys = `-- name: CountSpaceApiKeys :one
SELECT COUNT(*) FROM app."apiKeys"
WHERE organization_id = $1
  AND space_id = $2
`

func (q *Queries) CountSpaceApiKeys(ctx context.Context, organizationID string, spaceID *string) (int64, error) {
	row := q.db.QueryRow(ctx, countSpaceApiKeys, organizationID, spaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSpacePermissionSets = `-- name: CountSpacePermissionSets :one
SELECT COUNT(*) FROM app.permissions
WHERE space_id = $1
`

func (q *Queries) CountSpacePermissionSets(ctx context.Context, spaceID *string) (int64, error) {
	row := q.db.QueryRow(ctx, countSpacePermissionSets, spaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO app."apiKeys" (
  id, organization_id, organization_permission_set_id,
  space_id, space_permission_set_id, name, created_by, expires_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, organization_id, organization_permission_set_id, space_id, space_permission_set_id, name, created_at, created_by, expires_at
`

type CreateApiKeyParams struct {
	ID                          string             `json:"id"`
	OrganizationID              string             `json:"organization_id"`
	OrganizationPermissionSetID *string            `json:"organization_permission_set_id"`
	SpaceID                     *string            `json:"space_id"`
	SpacePermissionSetID        *string            `json:"space_permission_set_id"`
	Name                        *string            `json:"name"`
	CreatedBy                   string             `json:"created_by"`
	ExpiresAt                   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (AppApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.ID,
		arg.OrganizationID,
		arg.OrganizationPermissionSetID,
		arg.SpaceID,
		arg.SpacePermissionSetID,
		arg.Name,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i AppApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OrganizationPermissionSetID,
		&i.SpaceID,
		&i.SpacePermissionSetID,
		&i.Name,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ExpiresAt,
	)
	return i, err
}

const createPermissionSet = `-- name: CreatePermissionSet :one
INSERT INTO app.permissions (
  id, organization_id, space_id, name, permissions, created_by, updated_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, organization_id, space_id, name, permissions, created_at, updated_at, created_by, updated_by
`

type CreatePermissionSetParams struct {
	ID             string   `json:"id"`
	OrganizationID string   `json:"organization_id"`
	SpaceID        *string  `json:"space_id"`
	Name           string   `json:"name"`
	Permissions    []string `json:"permissions"`
	CreatedBy      string   `json:"created_by"`
	UpdatedBy      string   `json:"updated_by"`
}

func (q *Queries) CreatePermissionSet(ctx context.Context, arg CreatePermissionSetParams) (AppPermission, error) {
	row := q.db.QueryRow(ctx, createPermissionSet,
		arg.ID,
		arg.OrganizationID,
		arg.SpaceID,
		arg.Name,
		arg.Permissions,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i AppPermission
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SpaceID,
		&i.Name,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteApiKey = `-- name: DeleteApiKey :exec
DELETE FROM app."apiKeys"
WHERE id = $1
`

func (q *Queries) DeleteApiKey(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteApiKey, id)
	return err
}

const deleteApiKeysBySpace = `-- name: DeleteApiKeysBySpace :exec
DELETE FROM app."apiKeys"
WHERE space_id = $1
`

func (q *Queries) DeleteApiKeysBySpace(ctx context.Context, spaceID *string) error {
	_, err := q.db.Exec(ctx, deleteApiKeysBySpace, spaceID)
	return err
}

const deleteExpiredApiKeys = `-- name: DeleteExpiredApiKeys :exec
DELETE FROM app."apiKeys"
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredApiKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredApiKeys)
	return err
}

const deletePermissionSet = `-- name: DeletePermissionSet :exec
DELETE FROM app.permissions
WHERE id = $1
`

func (q *Queries) DeletePermissionSet(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePermissionSet, id)
	return err
}

const deletePermissionSetsBySpace = `-- name: DeletePermissionSetsBySpace :exec
DELETE FROM app.permissions
WHERE space_id = $1
`

func (q *Queries) DeletePermissionSetsBySpace(ctx context.Context, spaceID *string) error {
	_, err := q.db.Exec(ctx, deletePermissionSetsBySpace, spaceID)
	return err
}

const getApiKey = `-- name: GetApiKey :one
SELECT id, organization_id, organization_permission_set_id, space_id, space_permission_set_id, name, created_at, created_by, expires_at FROM app."apiKeys"
WHERE id = $1
`

func (q *Queries) GetApiKey(ctx context.Context, id string) (AppApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKey, id)
	var i AppApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OrganizationPermissionSetID,
		&i.SpaceID,
		&i.SpacePermissionSetID,
		&i.Name,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ExpiresAt,
	)
	return i, err
}

const getPermissionSet = `-- name: GetPermissionSet :one
SELECT id, organization_id, space_id, name, permissions, created_at, updated_at, created_by, updated_by FROM app.permissions
WHERE id = $1
`

func (q *Queries) GetPermissionSet(ctx context.Context, id string) (AppPermission, error) {
	row := q.db.QueryRow(ctx, getPermissionSet, id)
	var i AppPermission
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SpaceID,
		&i.Name,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listApiKeysByOrganization = `-- name: ListApiKeysByOrganization :many
SELECT id, organization_id, organization_permission_set_id, space_id, space_permission_set_id, name, created_at, created_by, expires_at FROM app."apiKeys"
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListApiKeysByOrganization(ctx context.Context, organizationID string) ([]AppApiKey, error) {
	rows, err := q.db.Query(ctx, listApiKeysByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppApiKey{}
	for rows.Next() {
		var i AppApiKey
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OrganizationPermissionSetID,
			&i.SpaceID,
			&i.SpacePermissionSetID,
			&i.Name,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApiKeysBySpace = `-- name: ListApiKeysBySpace :many
SELECT id, organization_id, organization_permission_set_id, space_id, space_permission_set_id, name, created_at, created_by, expires_at FROM app."apiKeys"
WHERE space_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListApiKeysBySpace(ctx context.Context, spaceID *string) ([]AppApiKey, error) {
	rows, err := q.db.Query(ctx, listApiKeysBySpace, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppApiKey{}
	for rows.Next() {
		var i AppApiKey
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OrganizationPermissionSetID,
			&i.SpaceID,
			&i.SpacePermissionSetID,
			&i.Name,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationApiKeysPaginated = `-- name: ListOrganizationApiKeysPaginated :many
SELECT id, organization_id, organization_permission_set_id, space_id, space_permission_set_id, name, created_at, created_by, expires_at FROM app."apiKeys"
WHERE organization_id = $1
  AND space_id IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) ListOrganizationApiKeysPaginated(ctx context.Context, organizationID string, limit int32, offset int32) ([]AppApiKey, error) {
	rows, err := q.db.Query(ctx, listOrganizationApiKeysPaginated, organizationID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppApiKey{}
	for rows.Next() {
		var i AppApiKey
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OrganizationPermissionSetID,
			&i.SpaceID,
			&i.SpacePermissionSetID,
			&i.Name,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationPermissionSets = `-- name: ListOrganizationPermissionSets :many
SELECT id, organization_id, space_id, name, permissions, created_at, updated_at, created_by, updated_by FROM app.permissions
WHERE organization_id = $1 AND space_id IS NULL
ORDER BY name
`

func (q *Queries) ListOrganizationPermissionSets(ctx context.Context, organizationID string) ([]AppPermission, error) {
	rows, err := q.db.Query(ctx, listOrganizationPermissionSets, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPermission{}
	for rows.Next() {
		var i AppPermission
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SpaceID,
			&i.Name,
			&i.Permissions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationPermissionSetsPaginated = `-- name: ListOrganizationPermissionSetsPaginated :many
SELECT id, organization_id, space_id, name, permissions, created_at, updated_at, created_by, updated_by FROM app.permissions
WHERE organization_id = $1
  AND space_id IS NULL
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) ListOrganizationPermissionSetsPaginated(ctx context.Context, organizationID string, limit int32, offset int32) ([]AppPermission, error) {
	rows, err := q.db.Query(ctx, listOrganizationPermissionSetsPaginated, organizationID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPermission{}
	for rows.Next() {
		var i AppPermission
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SpaceID,
			&i.Name,
			&i.Permissions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpaceApiKeysPaginated = `-- name: ListSpaceApiKeysPaginated :many
SELECT id, organization_id, organization_permission_set_id, space_id, space_permission_set_id, name, created_at, created_by, expires_at FROM app."apiKeys"
WHERE organization_id = $1
  AND space_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

func (q *Queries) ListSpaceApiKeysPaginated(ctx context.Context, organizationID string, spaceID *string, limit int32, offset int32) ([]AppApiKey, error) {
	rows, err := q.db.Query(ctx, listSpaceApiKeysPaginated,
		organizationID,
		spaceID,
		limit,
		offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppApiKey{}
	for rows.Next() {
		var i AppApiKey
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OrganizationPermissionSetID,
			&i.SpaceID,
			&i.SpacePermissionSetID,
			&i.Name,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpacePermissionSets = `-- name: ListSpacePermissionSets :many
SELECT id, organization_id, space_id, name, permissions, created_at, updated_at, created_by, updated_by FROM app.permissions
WHERE space_id = $1
ORDER BY name
`

func (q *Queries) ListSpacePermissionSets(ctx context.Context, spaceID *string) ([]AppPermission, error) {
	rows, err := q.db.Query(ctx, listSpacePermissionSets, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPermission{}
	for rows.Next() {
		var i AppPermission
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SpaceID,
			&i.Name,
			&i.Permissions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpacePermissionSetsPaginated = `-- name: ListSpacePermissionSetsPaginated :many
SELECT id, organization_id, space_id, name, permissions, created_at, updated_at, created_by, updated_by FROM app.permissions
WHERE space_id = $1
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) ListSpacePermissionSetsPaginated(ctx context.Context, spaceID *string, limit int32, offset int32) ([]AppPermission, error) {
	rows, err := q.db.Query(ctx, listSpacePermissionSetsPaginated, spaceID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppPermission{}
	for rows.Next() {
		var i AppPermission
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SpaceID,
			&i.Name,
			&i.Permissions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePermissionSet = `-- name: UpdatePermissionSet :one
UPDATE app.permissions
SET name = $2,
    permissions = $3,
    updated_by = $4,
    space_id = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, space_id, name, permissions, created_at, updated_at, created_by, updated_by
`

func (q *Queries) UpdatePermissionSet(ctx context.Context, iD string, name string, permissions []string, updatedBy string, spaceID *string) (AppPermission, error) {
	row := q.db.QueryRow(ctx, updatePermissionSet,
		iD,
		name,
		permissions,
		updatedBy,
		spaceID,
	)
	var i AppPermission
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SpaceID,
		&i.Name,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
