// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policies.sql

package db

import (
	"context"
)

const countPolicies = `-- name: CountPolicies :one
SELECT COUNT(*)
FROM app.certificates
WHERE space_id = $1
`

func (q *Queries) CountPolicies(ctx context.Context, spaceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPolicies, spaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCertificateInSpace = `-- name: GetCertificateInSpace :one
SELECT id, name, space_id, policy, revoke
FROM app.certificates
WHERE id = $1
  AND space_id = $2
`

func (q *Queries) GetCertificateInSpace(ctx context.Context, iD string, spaceID string) (AppCertificate, error) {
	row := q.db.QueryRow(ctx, getCertificateInSpace, iD, spaceID)
	var i AppCertificate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SpaceID,
		&i.Policy,
		&i.Revoke,
	)
	return i, err
}

const listPoliciesPaginated = `-- name: ListPoliciesPaginated :many
SELECT id, name, space_id, policy, revoke
FROM app.certificates
WHERE space_id = $1
ORDER BY id
LIMIT $2 OFFSET $3
`

func (q *Queries) ListPoliciesPaginated(ctx context.Context, spaceID string, limit int32, offset int32) ([]AppCertificate, error) {
	rows, err := q.db.Query(ctx, listPoliciesPaginated, spaceID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppCertificate{}
	for rows.Next() {
		var i AppCertificate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SpaceID,
			&i.Policy,
			&i.Revoke,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePolicy = `-- name: UpdatePolicy :one
UPDATE app.certificates
SET policy = $3,
    revoke = $4,
    updated_at = NOW()
WHERE id = $1
  AND space_id = $2
RETURNING id, name, space_id, policy, revoke
`

func (q *Queries) UpdatePolicy(ctx context.Context, iD string, spaceID string, policy []byte, revoke bool) (AppCertificate, error) {
	row := q.db.QueryRow(ctx, updatePolicy,
		iD,
		spaceID,
		policy,
		revoke,
	)
	var i AppCertificate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SpaceID,
		&i.Policy,
		&i.Revoke,
	)
	return i, err
}
