// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"
)

type Querier interface {
	ApplyTag(ctx context.Context, arg ApplyTagParams) (AppAppliedTag, error)
	CountAppliedTagsByTag(ctx context.Context, tagID string) (int64, error)
	CountChannelsFiltered(ctx context.Context, spaceID string, column2 string, column3 []string) (int64, error)
	CountModelsFiltered(ctx context.Context, spaceID string, column2 string, column3 []string) (int64, error)
	CountOrganizationAdmins(ctx context.Context, organizationID string) (int64, error)
	CountOrganizationApiKeys(ctx context.Context, organizationID string) (int64, error)
	CountOrganizationMembersWithFilter(ctx context.Context, organizationID string, column2 interface{}) (int64, error)
	CountOrganizationPermissionSets(ctx context.Context, organizationID string) (int64, error)
	CountPolicies(ctx context.Context, spaceID string) (int64, error)
	CountSpaceApiKeys(ctx context.Context, organizationID string, spaceID *string) (int64, error)
	CountSpacePermissionSets(ctx context.Context, spaceID *string) (int64, error)
	CountSpacesByOrganization(ctx context.Context, organizationID string) (int64, error)
	CountThingsFiltered(ctx context.Context, spaceID string, column2 string, column3 string, column4 []string) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (AppAccount, error)
	CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (AppApiKey, error)
	CreateAuthToken(ctx context.Context, userID string, token string, type_ AppAuthTokenType, expiresAt time.Time) (AppAuthToken, error)
	CreateCertificate(ctx context.Context, iD string, name string, policy []byte, spaceID string) (AppCertificate, error)
	CreateChannel(ctx context.Context, arg CreateChannelParams) (AppChannel, error)
	CreateModel(ctx context.Context, arg CreateModelParams) (AppModel, error)
	CreateOrganization(ctx context.Context, iD string, name string, createdBy string, updatedBy string) (AppOrganization, error)
	CreateOrganizationMember(ctx context.Context, organizationID string, userID string, role AppOrganizationRole, organizationPermissionSetID string) (AppOrganizationMember, error)
	CreatePermissionSet(ctx context.Context, arg CreatePermissionSetParams) (AppPermission, error)
	CreateSession(ctx context.Context, sessionToken string, userID string, expires time.Time) (AppSession, error)
	CreateSpace(ctx context.Context, iD string, organizationID string, name string, createdBy string, updatedBy string) (AppSpace, error)
	CreateTag(ctx context.Context, iD string, name string, spaceID string, createdBy string, updatedBy string) (AppTag, error)
	CreateThing(ctx context.Context, arg CreateThingParams) (AppThing, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (AppUser, error)
	DeleteAccount(ctx context.Context, id string) error
	DeleteApiKey(ctx context.Context, id string) error
	DeleteApiKeysBySpace(ctx context.Context, spaceID *string) error
	DeleteAuthToken(ctx context.Context, token string) error
	DeleteAuthTokensByUser(ctx context.Context, userID string, type_ AppAuthTokenType) error
	DeleteCertificatesBySpace(ctx context.Context, spaceID string) error
	DeleteChannel(ctx context.Context, id string) error
	DeleteChannelsBySpace(ctx context.Context, spaceID string) error
	DeleteExpiredApiKeys(ctx context.Context) error
	DeleteExpiredAuthTokens(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteModel(ctx context.Context, id string) error
	DeleteModelsBySpace(ctx context.Context, spaceID string) error
	DeleteOrganization(ctx context.Context, id string) error
	DeleteOrganizationApiKeys(ctx context.Context, organizationID string) error
	DeleteOrganizationMember(ctx context.Context, id string) error
	DeleteOrganizationMemberByOrgAndUser(ctx context.Context, organizationID string, userID string) error
	DeleteOrganizationMembers(ctx context.Context, organizationID string) error
	DeleteOrganizationPermissionSets(ctx context.Context, organizationID string) error
	DeletePermissionSet(ctx context.Context, id string) error
	DeletePermissionSetsBySpace(ctx context.Context, spaceID *string) error
	DeleteSession(ctx context.Context, sessionToken string) error
	DeleteSpace(ctx context.Context, id string) error
	DeleteTag(ctx context.Context, id string) error
	DeleteThing(ctx context.Context, id string) error
	DeleteThingsBySpace(ctx context.Context, spaceID string) error
	DeleteUser(ctx context.Context, id string) error
	GetAccount(ctx context.Context, provider string, providerAccountID string) (AppAccount, error)
	GetAccountsByUser(ctx context.Context, userID string) ([]AppAccount, error)
	GetApiKey(ctx context.Context, id string) (AppApiKey, error)
	GetAuthToken(ctx context.Context, token string) (AppAuthToken, error)
	GetAuthTokenWithUser(ctx context.Context, token string) (GetAuthTokenWithUserRow, error)
	GetCertificate(ctx context.Context, id string) (AppCertificate, error)
	GetCertificateInSpace(ctx context.Context, iD string, spaceID string) (AppCertificate, error)
	GetChannel(ctx context.Context, id string) (AppChannel, error)
	GetDefaultOrganizationPermissionSet(ctx context.Context, organizationID string) (AppPermission, error)
	GetModel(ctx context.Context, id string) (AppModel, error)
	GetOrganization(ctx context.Context, id string) (AppOrganization, error)
	GetOrganizationMember(ctx context.Context, organizationID string, userID string) (AppOrganizationMember, error)
	GetPermissionSet(ctx context.Context, id string) (AppPermission, error)
	GetSession(ctx context.Context, sessionToken string) (AppSession, error)
	GetSessionWithUser(ctx context.Context, sessionToken string) (GetSessionWithUserRow, error)
	GetSpace(ctx context.Context, id string) (AppSpace, error)
	GetSpaceWithOrganization(ctx context.Context, id string) (GetSpaceWithOrganizationRow, error)
	GetTag(ctx context.Context, id string) (AppTag, error)
	GetThing(ctx context.Context, id string) (AppThing, error)
	GetUser(ctx context.Context, id string) (AppUser, error)
	GetUserByEmail(ctx context.Context, email *string) (AppUser, error)
	GetUserWithOrganizations(ctx context.Context, id string) ([]GetUserWithOrganizationsRow, error)
	ListApiKeysByOrganization(ctx context.Context, organizationID string) ([]AppApiKey, error)
	ListApiKeysBySpace(ctx context.Context, spaceID *string) ([]AppApiKey, error)
	ListAppliedTagsByChannel(ctx context.Context, channelID *string) ([]ListAppliedTagsByChannelRow, error)
	ListAppliedTagsByModel(ctx context.Context, modelID *string) ([]ListAppliedTagsByModelRow, error)
	ListAppliedTagsByTag(ctx context.Context, tagID string) ([]AppAppliedTag, error)
	ListAppliedTagsByThing(ctx context.Context, thingID *string) ([]ListAppliedTagsByThingRow, error)
	ListChannels(ctx context.Context, spaceID string) ([]AppChannel, error)
	ListChannelsFiltered(ctx context.Context, spaceID string, column2 string, column3 []string, limit int32, offset int32) ([]AppChannel, error)
	ListInternalThings(ctx context.Context, spaceID string) ([]AppThing, error)
	ListModels(ctx context.Context, spaceID string) ([]AppModel, error)
	ListModelsFiltered(ctx context.Context, spaceID string, column2 string, column3 []string, limit int32, offset int32) ([]AppModel, error)
	ListOrganizationApiKeysPaginated(ctx context.Context, organizationID string, limit int32, offset int32) ([]AppApiKey, error)
	ListOrganizationMembers(ctx context.Context, organizationID string) ([]ListOrganizationMembersRow, error)
	ListOrganizationMembersWithFilter(ctx context.Context, organizationID string, column2 interface{}, limit int32, offset int32) ([]ListOrganizationMembersWithFilterRow, error)
	ListOrganizationPermissionSets(ctx context.Context, organizationID string) ([]AppPermission, error)
	ListOrganizationPermissionSetsPaginated(ctx context.Context, organizationID string, limit int32, offset int32) ([]AppPermission, error)
	ListOrganizations(ctx context.Context) ([]AppOrganization, error)
	ListPoliciesPaginated(ctx context.Context, spaceID string, limit int32, offset int32) ([]AppCertificate, error)
	ListPublishedChannels(ctx context.Context, spaceID string) ([]AppChannel, error)
	ListSpaceApiKeysPaginated(ctx context.Context, organizationID string, spaceID *string, limit int32, offset int32) ([]AppApiKey, error)
	ListSpacePermissionSets(ctx context.Context, spaceID *string) ([]AppPermission, error)
	ListSpacePermissionSetsPaginated(ctx context.Context, spaceID *string, limit int32, offset int32) ([]AppPermission, error)
	ListSpaces(ctx context.Context, organizationID string) ([]AppSpace, error)
	ListTags(ctx context.Context, spaceID string) ([]AppTag, error)
	ListThings(ctx context.Context, spaceID string) ([]AppThing, error)
	ListThingsByCategory(ctx context.Context, spaceID string, thingCategory string) ([]AppThing, error)
	ListThingsFiltered(ctx context.Context, arg ListThingsFilteredParams) ([]AppThing, error)
	ListUserOrganizationMembers(ctx context.Context, userID string) ([]ListUserOrganizationMembersRow, error)
	ListUsers(ctx context.Context) ([]AppUser, error)
	PublishChannel(ctx context.Context, iD string, publishedBy *string) (AppChannel, error)
	RemoveAppliedTag(ctx context.Context, id string) error
	RemoveAppliedTagBySubject(ctx context.Context, tagID string, thingID *string) error
	SearchUsers(ctx context.Context, organizationID string, query *string) ([]AppUser, error)
	UnpublishChannel(ctx context.Context, id string) (AppChannel, error)
	UpdateChannel(ctx context.Context, iD string, name string, config []byte, updatedBy string) (AppChannel, error)
	UpdateChannelConfig(ctx context.Context, iD string, config []byte, updatedBy string) (AppChannel, error)
	UpdateModel(ctx context.Context, iD string, name string, attributes []byte, updatedBy string) (AppModel, error)
	UpdateOrganization(ctx context.Context, iD string, name string, updatedBy string) (AppOrganization, error)
	UpdateOrganizationMemberRole(ctx context.Context, iD string, role AppOrganizationRole) (AppOrganizationMember, error)
	UpdateOrganizationMemberRoleByOrgAndUser(ctx context.Context, organizationID string, userID string, role AppOrganizationRole) (AppOrganizationMember, error)
	UpdatePermissionSet(ctx context.Context, iD string, name string, permissions []string, updatedBy string, spaceID *string) (AppPermission, error)
	UpdatePolicy(ctx context.Context, iD string, spaceID string, policy []byte, revoke bool) (AppCertificate, error)
	UpdateSession(ctx context.Context, sessionToken string, expires time.Time) (AppSession, error)
	UpdateSpace(ctx context.Context, iD string, name string, updatedBy string) (AppSpace, error)
	UpdateTag(ctx context.Context, iD string, name string, updatedBy string) (AppTag, error)
	UpdateThing(ctx context.Context, iD string, name string, attributes []byte, updatedBy string) (AppThing, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (AppUser, error)
	UpdateUserPassword(ctx context.Context, iD string, password *string) (AppUser, error)
	VerifyUserEmail(ctx context.Context, id string) (AppUser, error)
}

var _ Querier = (*Queries)(nil)
