// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spaces.sql

package db

import (
	"context"
	"time"
)

const countSpacesByOrganization = `-- name: CountSpacesByOrganization :one
SELECT COUNT(*) FROM app.spaces
WHERE organization_id = $1
`

func (q *Queries) CountSpacesByOrganization(ctx context.Context, organizationID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSpacesByOrganization, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSpace = `-- name: CreateSpace :one
INSERT INTO app.spaces (
  id, organization_id, name, created_by, updated_by
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, organization_id, name, created_at, created_by, updated_at, updated_by
`

func (q *Queries) CreateSpace(ctx context.Context, iD string, organizationID string, name string, createdBy string, updatedBy string) (AppSpace, error) {
	row := q.db.QueryRow(ctx, createSpace,
		iD,
		organizationID,
		name,
		createdBy,
		updatedBy,
	)
	var i AppSpace
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteSpace = `-- name: DeleteSpace :exec
DELETE FROM app.spaces
WHERE id = $1
`

func (q *Queries) DeleteSpace(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSpace, id)
	return err
}

const getSpace = `-- name: GetSpace :one
SELECT id, organization_id, name, created_at, created_by, updated_at, updated_by FROM app.spaces
WHERE id = $1
`

func (q *Queries) GetSpace(ctx context.Context, id string) (AppSpace, error) {
	row := q.db.QueryRow(ctx, getSpace, id)
	var i AppSpace
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getSpaceWithOrganization = `-- name: GetSpaceWithOrganization :one
SELECT 
  s.id, s.organization_id, s.name, s.created_at, s.created_by, s.updated_at, s.updated_by,
  o.name as organization_name
FROM app.spaces s
JOIN app.organizations o ON s.organization_id = o.id
WHERE s.id = $1
`

type GetSpaceWithOrganizationRow struct {
	ID               string    `json:"id"`
	OrganizationID   string    `json:"organization_id"`
	Name             string    `json:"name"`
	CreatedAt        time.Time `json:"created_at"`
	CreatedBy        string    `json:"created_by"`
	UpdatedAt        time.Time `json:"updated_at"`
	UpdatedBy        string    `json:"updated_by"`
	OrganizationName string    `json:"organization_name"`
}

func (q *Queries) GetSpaceWithOrganization(ctx context.Context, id string) (GetSpaceWithOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getSpaceWithOrganization, id)
	var i GetSpaceWithOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.OrganizationName,
	)
	return i, err
}

const listSpaces = `-- name: ListSpaces :many
SELECT id, organization_id, name, created_at, created_by, updated_at, updated_by FROM app.spaces
WHERE organization_id = $1
ORDER BY name
`

func (q *Queries) ListSpaces(ctx context.Context, organizationID string) ([]AppSpace, error) {
	rows, err := q.db.Query(ctx, listSpaces, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSpace{}
	for rows.Next() {
		var i AppSpace
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpace = `-- name: UpdateSpace :one
UPDATE app.spaces
SET name = $2,
    updated_by = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, name, created_at, created_by, updated_at, updated_by
`

func (q *Queries) UpdateSpace(ctx context.Context, iD string, name string, updatedBy string) (AppSpace, error) {
	row := q.db.QueryRow(ctx, updateSpace, iD, name, updatedBy)
	var i AppSpace
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
