// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"
	"time"
)

const applyTag = `-- name: ApplyTag :one
INSERT INTO app.applied_tags (
  space_id, tag_id, channel_id, model_id, thing_id, created_by, updated_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, space_id, tag_id, channel_id, model_id, thing_id, created_at, updated_at, created_by, updated_by
`

type ApplyTagParams struct {
	SpaceID   string  `json:"space_id"`
	TagID     string  `json:"tag_id"`
	ChannelID *string `json:"channel_id"`
	ModelID   *string `json:"model_id"`
	ThingID   *string `json:"thing_id"`
	CreatedBy string  `json:"created_by"`
	UpdatedBy string  `json:"updated_by"`
}

func (q *Queries) ApplyTag(ctx context.Context, arg ApplyTagParams) (AppAppliedTag, error) {
	row := q.db.QueryRow(ctx, applyTag,
		arg.SpaceID,
		arg.TagID,
		arg.ChannelID,
		arg.ModelID,
		arg.ThingID,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i AppAppliedTag
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.TagID,
		&i.ChannelID,
		&i.ModelID,
		&i.ThingID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const countAppliedTagsByTag = `-- name: CountAppliedTagsByTag :one
SELECT COUNT(*)::bigint
FROM app.applied_tags
WHERE tag_id = $1
`

func (q *Queries) CountAppliedTagsByTag(ctx context.Context, tagID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAppliedTagsByTag, tagID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO app.tags (
  id, name, space_id, created_by, updated_by
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, name, space_id, created_at, updated_at, created_by, updated_by
`

func (q *Queries) CreateTag(ctx context.Context, iD string, name string, spaceID string, createdBy string, updatedBy string) (AppTag, error) {
	row := q.db.QueryRow(ctx, createTag,
		iD,
		name,
		spaceID,
		createdBy,
		updatedBy,
	)
	var i AppTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SpaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM app.tags
WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, name, space_id, created_at, updated_at, created_by, updated_by FROM app.tags
WHERE id = $1
`

func (q *Queries) GetTag(ctx context.Context, id string) (AppTag, error) {
	row := q.db.QueryRow(ctx, getTag, id)
	var i AppTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SpaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listAppliedTagsByChannel = `-- name: ListAppliedTagsByChannel :many
SELECT 
  at.id, at.space_id, at.tag_id, at.channel_id, at.model_id, at.thing_id, at.created_at, at.updated_at, at.created_by, at.updated_by,
  t.name as tag_name
FROM app.applied_tags at
JOIN app.tags t ON at.tag_id = t.id
WHERE at.channel_id = $1
`

type ListAppliedTagsByChannelRow struct {
	ID        string    `json:"id"`
	SpaceID   string    `json:"space_id"`
	TagID     string    `json:"tag_id"`
	ChannelID *string   `json:"channel_id"`
	ModelID   *string   `json:"model_id"`
	ThingID   *string   `json:"thing_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	CreatedBy string    `json:"created_by"`
	UpdatedBy string    `json:"updated_by"`
	TagName   string    `json:"tag_name"`
}

func (q *Queries) ListAppliedTagsByChannel(ctx context.Context, channelID *string) ([]ListAppliedTagsByChannelRow, error) {
	rows, err := q.db.Query(ctx, listAppliedTagsByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppliedTagsByChannelRow{}
	for rows.Next() {
		var i ListAppliedTagsByChannelRow
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.TagID,
			&i.ChannelID,
			&i.ModelID,
			&i.ThingID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TagName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppliedTagsByModel = `-- name: ListAppliedTagsByModel :many
SELECT 
  at.id, at.space_id, at.tag_id, at.channel_id, at.model_id, at.thing_id, at.created_at, at.updated_at, at.created_by, at.updated_by,
  t.name as tag_name
FROM app.applied_tags at
JOIN app.tags t ON at.tag_id = t.id
WHERE at.model_id = $1
`

type ListAppliedTagsByModelRow struct {
	ID        string    `json:"id"`
	SpaceID   string    `json:"space_id"`
	TagID     string    `json:"tag_id"`
	ChannelID *string   `json:"channel_id"`
	ModelID   *string   `json:"model_id"`
	ThingID   *string   `json:"thing_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	CreatedBy string    `json:"created_by"`
	UpdatedBy string    `json:"updated_by"`
	TagName   string    `json:"tag_name"`
}

func (q *Queries) ListAppliedTagsByModel(ctx context.Context, modelID *string) ([]ListAppliedTagsByModelRow, error) {
	rows, err := q.db.Query(ctx, listAppliedTagsByModel, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppliedTagsByModelRow{}
	for rows.Next() {
		var i ListAppliedTagsByModelRow
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.TagID,
			&i.ChannelID,
			&i.ModelID,
			&i.ThingID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TagName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppliedTagsByTag = `-- name: ListAppliedTagsByTag :many
SELECT id, space_id, tag_id, channel_id, model_id, thing_id, created_at, updated_at, created_by, updated_by FROM app.applied_tags
WHERE tag_id = $1
`

func (q *Queries) ListAppliedTagsByTag(ctx context.Context, tagID string) ([]AppAppliedTag, error) {
	rows, err := q.db.Query(ctx, listAppliedTagsByTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppAppliedTag{}
	for rows.Next() {
		var i AppAppliedTag
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.TagID,
			&i.ChannelID,
			&i.ModelID,
			&i.ThingID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppliedTagsByThing = `-- name: ListAppliedTagsByThing :many
SELECT 
  at.id, at.space_id, at.tag_id, at.channel_id, at.model_id, at.thing_id, at.created_at, at.updated_at, at.created_by, at.updated_by,
  t.name as tag_name
FROM app.applied_tags at
JOIN app.tags t ON at.tag_id = t.id
WHERE at.thing_id = $1
`

type ListAppliedTagsByThingRow struct {
	ID        string    `json:"id"`
	SpaceID   string    `json:"space_id"`
	TagID     string    `json:"tag_id"`
	ChannelID *string   `json:"channel_id"`
	ModelID   *string   `json:"model_id"`
	ThingID   *string   `json:"thing_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	CreatedBy string    `json:"created_by"`
	UpdatedBy string    `json:"updated_by"`
	TagName   string    `json:"tag_name"`
}

func (q *Queries) ListAppliedTagsByThing(ctx context.Context, thingID *string) ([]ListAppliedTagsByThingRow, error) {
	rows, err := q.db.Query(ctx, listAppliedTagsByThing, thingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppliedTagsByThingRow{}
	for rows.Next() {
		var i ListAppliedTagsByThingRow
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.TagID,
			&i.ChannelID,
			&i.ModelID,
			&i.ThingID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TagName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, space_id, created_at, updated_at, created_by, updated_by FROM app.tags
WHERE space_id = $1
ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context, spaceID string) ([]AppTag, error) {
	rows, err := q.db.Query(ctx, listTags, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppTag{}
	for rows.Next() {
		var i AppTag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SpaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAppliedTag = `-- name: RemoveAppliedTag :exec
DELETE FROM app.applied_tags
WHERE id = $1
`

func (q *Queries) RemoveAppliedTag(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, removeAppliedTag, id)
	return err
}

const removeAppliedTagBySubject = `-- name: RemoveAppliedTagBySubject :exec
DELETE FROM app.applied_tags
WHERE tag_id = $1
  AND (
    thing_id = $2
    OR channel_id = $2
    OR model_id = $2
  )
`

func (q *Queries) RemoveAppliedTagBySubject(ctx context.Context, tagID string, thingID *string) error {
	_, err := q.db.Exec(ctx, removeAppliedTagBySubject, tagID, thingID)
	return err
}

const updateTag = `-- name: UpdateTag :one
UPDATE app.tags
SET name = $2,
    updated_by = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, space_id, created_at, updated_at, created_by, updated_by
`

func (q *Queries) UpdateTag(ctx context.Context, iD string, name string, updatedBy string) (AppTag, error) {
	row := q.db.QueryRow(ctx, updateTag, iD, name, updatedBy)
	var i AppTag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SpaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
