// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: things.sql

package db

import (
	"context"
)

const countThingsFiltered = `-- name: CountThingsFiltered :one
SELECT COUNT(DISTINCT t.id)
FROM app.things t
WHERE t.space_id = $1
  AND t.internal = false
  AND ($2::text IS NULL OR t.thing_category = $2)
  AND (
    $3::text IS NULL
    OR t.id ILIKE $3
    OR t.name ILIKE $3
    OR t.thing_category ILIKE $3
  )
  AND (
    $4::text[] IS NULL
    OR EXISTS (
      SELECT 1
      FROM app.applied_tags at
      WHERE at.thing_id = t.id
        AND at.tag_id = ANY($4::text[])
    )
  )
`

func (q *Queries) CountThingsFiltered(ctx context.Context, spaceID string, column2 string, column3 string, column4 []string) (int64, error) {
	row := q.db.QueryRow(ctx, countThingsFiltered,
		spaceID,
		column2,
		column3,
		column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCertificate = `-- name: CreateCertificate :one
INSERT INTO app.certificates (
  id, name, policy, space_id
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, name, space_id, policy, revoke
`

func (q *Queries) CreateCertificate(ctx context.Context, iD string, name string, policy []byte, spaceID string) (AppCertificate, error) {
	row := q.db.QueryRow(ctx, createCertificate,
		iD,
		name,
		policy,
		spaceID,
	)
	var i AppCertificate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SpaceID,
		&i.Policy,
		&i.Revoke,
	)
	return i, err
}

const createThing = `-- name: CreateThing :one
INSERT INTO app.things (
  id, name, space_id, attributes, internal, thing_category, created_by, updated_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, name, space_id, attributes, internal, created_at, updated_at, created_by, updated_by, thing_category
`

type CreateThingParams struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	SpaceID       string `json:"space_id"`
	Attributes    []byte `json:"attributes"`
	Internal      bool   `json:"internal"`
	ThingCategory string `json:"thing_category"`
	CreatedBy     string `json:"created_by"`
	UpdatedBy     string `json:"updated_by"`
}

func (q *Queries) CreateThing(ctx context.Context, arg CreateThingParams) (AppThing, error) {
	row := q.db.QueryRow(ctx, createThing,
		arg.ID,
		arg.Name,
		arg.SpaceID,
		arg.Attributes,
		arg.Internal,
		arg.ThingCategory,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i AppThing
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SpaceID,
		&i.Attributes,
		&i.Internal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.ThingCategory,
	)
	return i, err
}

const deleteCertificatesBySpace = `-- name: DeleteCertificatesBySpace :exec
DELETE FROM app.certificates
WHERE space_id = $1
`

func (q *Queries) DeleteCertificatesBySpace(ctx context.Context, spaceID string) error {
	_, err := q.db.Exec(ctx, deleteCertificatesBySpace, spaceID)
	return err
}

const deleteThing = `-- name: DeleteThing :exec
DELETE FROM app.things
WHERE id = $1
`

func (q *Queries) DeleteThing(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteThing, id)
	return err
}

const deleteThingsBySpace = `-- name: DeleteThingsBySpace :exec
DELETE FROM app.things
WHERE space_id = $1
`

func (q *Queries) DeleteThingsBySpace(ctx context.Context, spaceID string) error {
	_, err := q.db.Exec(ctx, deleteThingsBySpace, spaceID)
	return err
}

const getCertificate = `-- name: GetCertificate :one
SELECT id, name, space_id, policy, revoke FROM app.certificates
WHERE id = $1
`

func (q *Queries) GetCertificate(ctx context.Context, id string) (AppCertificate, error) {
	row := q.db.QueryRow(ctx, getCertificate, id)
	var i AppCertificate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SpaceID,
		&i.Policy,
		&i.Revoke,
	)
	return i, err
}

const getThing = `-- name: GetThing :one
SELECT id, name, space_id, attributes, internal, created_at, updated_at, created_by, updated_by, thing_category FROM app.things
WHERE id = $1
`

func (q *Queries) GetThing(ctx context.Context, id string) (AppThing, error) {
	row := q.db.QueryRow(ctx, getThing, id)
	var i AppThing
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SpaceID,
		&i.Attributes,
		&i.Internal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.ThingCategory,
	)
	return i, err
}

const listInternalThings = `-- name: ListInternalThings :many
SELECT id, name, space_id, attributes, internal, created_at, updated_at, created_by, updated_by, thing_category FROM app.things
WHERE space_id = $1 AND internal = true
ORDER BY name
`

func (q *Queries) ListInternalThings(ctx context.Context, spaceID string) ([]AppThing, error) {
	rows, err := q.db.Query(ctx, listInternalThings, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppThing{}
	for rows.Next() {
		var i AppThing
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SpaceID,
			&i.Attributes,
			&i.Internal,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.ThingCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThings = `-- name: ListThings :many
SELECT id, name, space_id, attributes, internal, created_at, updated_at, created_by, updated_by, thing_category FROM app.things
WHERE space_id = $1
ORDER BY name
`

func (q *Queries) ListThings(ctx context.Context, spaceID string) ([]AppThing, error) {
	rows, err := q.db.Query(ctx, listThings, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppThing{}
	for rows.Next() {
		var i AppThing
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SpaceID,
			&i.Attributes,
			&i.Internal,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.ThingCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThingsByCategory = `-- name: ListThingsByCategory :many
SELECT id, name, space_id, attributes, internal, created_at, updated_at, created_by, updated_by, thing_category FROM app.things
WHERE space_id = $1 AND thing_category = $2
ORDER BY name
`

func (q *Queries) ListThingsByCategory(ctx context.Context, spaceID string, thingCategory string) ([]AppThing, error) {
	rows, err := q.db.Query(ctx, listThingsByCategory, spaceID, thingCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppThing{}
	for rows.Next() {
		var i AppThing
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SpaceID,
			&i.Attributes,
			&i.Internal,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.ThingCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThingsFiltered = `-- name: ListThingsFiltered :many
SELECT t.id, t.name, t.space_id, t.attributes, t.internal, t.created_at, t.updated_at, t.created_by, t.updated_by, t.thing_category
FROM app.things t
WHERE t.space_id = $1
  AND t.internal = false
  AND ($2::text IS NULL OR t.thing_category = $2)
  AND (
    $3::text IS NULL
    OR t.id ILIKE $3
    OR t.name ILIKE $3
    OR t.thing_category ILIKE $3
  )
  AND (
    $4::text[] IS NULL
    OR EXISTS (
      SELECT 1
      FROM app.applied_tags at
      WHERE at.thing_id = t.id
        AND at.tag_id = ANY($4::text[])
    )
  )
ORDER BY t.thing_category DESC
LIMIT $5 OFFSET $6
`

type ListThingsFilteredParams struct {
	SpaceID string   `json:"space_id"`
	Column2 string   `json:"column_2"`
	Column3 string   `json:"column_3"`
	Column4 []string `json:"column_4"`
	Limit   int32    `json:"limit"`
	Offset  int32    `json:"offset"`
}

func (q *Queries) ListThingsFiltered(ctx context.Context, arg ListThingsFilteredParams) ([]AppThing, error) {
	rows, err := q.db.Query(ctx, listThingsFiltered,
		arg.SpaceID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppThing{}
	for rows.Next() {
		var i AppThing
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SpaceID,
			&i.Attributes,
			&i.Internal,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.ThingCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateThing = `-- name: UpdateThing :one
UPDATE app.things
SET name = $2,
    attributes = $3,
    updated_by = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, space_id, attributes, internal, created_at, updated_at, created_by, updated_by, thing_category
`

func (q *Queries) UpdateThing(ctx context.Context, iD string, name string, attributes []byte, updatedBy string) (AppThing, error) {
	row := q.db.QueryRow(ctx, updateThing,
		iD,
		name,
		attributes,
		updatedBy,
	)
	var i AppThing
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SpaceID,
		&i.Attributes,
		&i.Internal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.ThingCategory,
	)
	return i, err
}
