// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO app.users (
  id, name, email, email_verified, password, image
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, name, email, email_verified, password, image
`

type CreateUserParams struct {
	ID            string             `json:"id"`
	Name          *string            `json:"name"`
	Email         *string            `json:"email"`
	EmailVerified pgtype.Timestamptz `json:"email_verified"`
	Password      *string            `json:"password"`
	Image         *string            `json:"image"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.EmailVerified,
		arg.Password,
		arg.Image,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Password,
		&i.Image,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM app.users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, email_verified, password, image FROM app.users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Password,
		&i.Image,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, email_verified, password, image FROM app.users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Password,
		&i.Image,
	)
	return i, err
}

const getUserWithOrganizations = `-- name: GetUserWithOrganizations :many
SELECT 
  u.id, u.name, u.email, u.email_verified, u.password, u.image,
  om.organization_id,
  om.role as organization_role,
  o.name as organization_name
FROM app.users u
LEFT JOIN app.organization_members om ON u.id = om.user_id
LEFT JOIN app.organizations o ON om.organization_id = o.id
WHERE u.id = $1
`

type GetUserWithOrganizationsRow struct {
	ID               string               `json:"id"`
	Name             *string              `json:"name"`
	Email            *string              `json:"email"`
	EmailVerified    pgtype.Timestamptz   `json:"email_verified"`
	Password         *string              `json:"password"`
	Image            *string              `json:"image"`
	OrganizationID   *string              `json:"organization_id"`
	OrganizationRole *AppOrganizationRole `json:"organization_role"`
	OrganizationName *string              `json:"organization_name"`
}

func (q *Queries) GetUserWithOrganizations(ctx context.Context, id string) ([]GetUserWithOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, getUserWithOrganizations, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserWithOrganizationsRow{}
	for rows.Next() {
		var i GetUserWithOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.EmailVerified,
			&i.Password,
			&i.Image,
			&i.OrganizationID,
			&i.OrganizationRole,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, email_verified, password, image FROM app.users
ORDER BY email
`

func (q *Queries) ListUsers(ctx context.Context) ([]AppUser, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppUser{}
	for rows.Next() {
		var i AppUser
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.EmailVerified,
			&i.Password,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT u.id, u.name, u.email, u.email_verified, u.password, u.image FROM app.users u
LEFT JOIN app.organization_members om
  ON om.user_id = u.id
 AND om.organization_id = $1
WHERE u.email ILIKE ('%' || $2 || '%')
  AND ($1 = '' OR om.user_id IS NULL)
ORDER BY u.email
`

func (q *Queries) SearchUsers(ctx context.Context, organizationID string, query *string) ([]AppUser, error) {
	rows, err := q.db.Query(ctx, searchUsers, organizationID, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppUser{}
	for rows.Next() {
		var i AppUser
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.EmailVerified,
			&i.Password,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE app.users
SET name = COALESCE($1, name),
    email = COALESCE($2, email),
    email_verified = COALESCE($3, email_verified),
    password = COALESCE($4, password),
    image = COALESCE($5, image)
WHERE id = $6
RETURNING id, name, email, email_verified, password, image
`

type UpdateUserParams struct {
	Name          *string            `json:"name"`
	Email         *string            `json:"email"`
	EmailVerified pgtype.Timestamptz `json:"email_verified"`
	Password      *string            `json:"password"`
	Image         *string            `json:"image"`
	ID            string             `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.EmailVerified,
		arg.Password,
		arg.Image,
		arg.ID,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Password,
		&i.Image,
	)
	return i, err
}

const verifyUserEmail = `-- name: VerifyUserEmail :one
UPDATE app.users
SET email_verified = NOW()
WHERE id = $1
RETURNING id, name, email, email_verified, password, image
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id string) (AppUser, error) {
	row := q.db.QueryRow(ctx, verifyUserEmail, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Password,
		&i.Image,
	)
	return i, err
}
