# Listen on standard unencrypted MQTT port
listener 1883

# Include all logs
log_type error
log_type warning
log_type notice
log_type information

# Allow connection of any "client id"
allow_anonymous true

# Log client connection and disconnection messages
connection_messages true

# Add a timestamp value to each log message.
log_timestamp true
