apiVersion: 1

datasources:
  - name: Clickhouse
    uid: ee6ijxacy70g0a
    type: grafana-clickhouse-datasource
    access: proxy
    url: ""
    user: ""
    database: ""
    basicAuth: false
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      username: iotea
      version: "4.5.1"
      defaultDatabase: platform
      logs:
        contextColumns: []
        defaultDatabase: platform
        defaultTable: otel_logs
        otelEnabled: true
        otelVersion: latest
        selectContext: true
      traces:
        defaultDatabase: platform
        defaultTable: otel_traces
        durationUnit: nanoseconds
        otelEnabled: true
        otelVersion: latest
    secureJsonData:
      password: iotea
    version: 3
    readOnly: false
  - name: InfluxDB
    uid: eeaqxbe9txywwa
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: iotea
      defaultBucket: default
    secureJsonData:
      token: my-secret-influxdb2-token
    isDefault: false