syntax = "proto3";
package collector;

import "google/protobuf/timestamp.proto";

option go_package = "https://github.com/iotea-com/IoTea/libs/protocols/collector";

// Services
service CollectorService {
    // Metrics
    rpc GetRuntimeMetrics (GetRuntimeMetricsRequest) returns (GetRuntimeMetricsResponse) {}
    rpc GetRuntimeExecutions (GetRuntimeExecutionsRequest) returns (GetRuntimeExecutionsResponse) {}
}

// Metrics
message Metrics {
    google.protobuf.Timestamp timestamp = 1;
    int64 cpuMilliCores = 2;
    int64 memoryBytes = 3;
    int64 networkTotalRxBytes = 4;
    int64 networkTotalTxBytes = 5;
}

message GetRuntimeMetricsRequest {
    string channelId = 1;
    google.protobuf.Timestamp startTime = 2;
    google.protobuf.Timestamp endTime = 3;
}

message GetRuntimeMetricsResponse {
    string error = 1;
    repeated Metrics metrics = 2;
}

// Executions
message NodeExecutionLog {
    string traceId = 1;
    string spanId = 2;
    google.protobuf.Timestamp timestamp = 3;
    string level = 4;
    string body = 5;
    map<string, string> logAttributes = 6;
    map<string, string> resourceAttributes = 7;
    string status = 8;
}

message Execution {
    string traceId = 1;
    google.protobuf.Timestamp startTime = 2;
    google.protobuf.Timestamp endTime = 3;
    int64 durationMs = 4;
    string channelId = 5;
    string status = 6;
    repeated NodeExecutionLog nodeExecutionLogs = 7;
}

message GetRuntimeExecutionsRequest {
    string channelId = 1;
    google.protobuf.Timestamp startTime = 2;
    google.protobuf.Timestamp endTime = 3;
}

message GetRuntimeExecutionsResponse {
    string error = 1;
    repeated Execution executions = 2;
}
