// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: collector.proto

package collector

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CollectorService_GetRuntimeMetrics_FullMethodName    = "/collector.CollectorService/GetRuntimeMetrics"
	CollectorService_GetRuntimeExecutions_FullMethodName = "/collector.CollectorService/GetRuntimeExecutions"
)

// CollectorServiceClient is the client API for CollectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Services
type CollectorServiceClient interface {
	// Metrics
	GetRuntimeMetrics(ctx context.Context, in *GetRuntimeMetricsRequest, opts ...grpc.CallOption) (*GetRuntimeMetricsResponse, error)
	GetRuntimeExecutions(ctx context.Context, in *GetRuntimeExecutionsRequest, opts ...grpc.CallOption) (*GetRuntimeExecutionsResponse, error)
}

type collectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectorServiceClient(cc grpc.ClientConnInterface) CollectorServiceClient {
	return &collectorServiceClient{cc}
}

func (c *collectorServiceClient) GetRuntimeMetrics(ctx context.Context, in *GetRuntimeMetricsRequest, opts ...grpc.CallOption) (*GetRuntimeMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuntimeMetricsResponse)
	err := c.cc.Invoke(ctx, CollectorService_GetRuntimeMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorServiceClient) GetRuntimeExecutions(ctx context.Context, in *GetRuntimeExecutionsRequest, opts ...grpc.CallOption) (*GetRuntimeExecutionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuntimeExecutionsResponse)
	err := c.cc.Invoke(ctx, CollectorService_GetRuntimeExecutions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectorServiceServer is the server API for CollectorService service.
// All implementations must embed UnimplementedCollectorServiceServer
// for forward compatibility.
//
// Services
type CollectorServiceServer interface {
	// Metrics
	GetRuntimeMetrics(context.Context, *GetRuntimeMetricsRequest) (*GetRuntimeMetricsResponse, error)
	GetRuntimeExecutions(context.Context, *GetRuntimeExecutionsRequest) (*GetRuntimeExecutionsResponse, error)
	mustEmbedUnimplementedCollectorServiceServer()
}

// UnimplementedCollectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCollectorServiceServer struct{}

func (UnimplementedCollectorServiceServer) GetRuntimeMetrics(context.Context, *GetRuntimeMetricsRequest) (*GetRuntimeMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRuntimeMetrics not implemented")
}
func (UnimplementedCollectorServiceServer) GetRuntimeExecutions(context.Context, *GetRuntimeExecutionsRequest) (*GetRuntimeExecutionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRuntimeExecutions not implemented")
}
func (UnimplementedCollectorServiceServer) mustEmbedUnimplementedCollectorServiceServer() {}
func (UnimplementedCollectorServiceServer) testEmbeddedByValue()                          {}

// UnsafeCollectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectorServiceServer will
// result in compilation errors.
type UnsafeCollectorServiceServer interface {
	mustEmbedUnimplementedCollectorServiceServer()
}

func RegisterCollectorServiceServer(s grpc.ServiceRegistrar, srv CollectorServiceServer) {
	// If the following call pancis, it indicates UnimplementedCollectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CollectorService_ServiceDesc, srv)
}

func _CollectorService_GetRuntimeMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuntimeMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).GetRuntimeMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectorService_GetRuntimeMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).GetRuntimeMetrics(ctx, req.(*GetRuntimeMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorService_GetRuntimeExecutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuntimeExecutionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).GetRuntimeExecutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectorService_GetRuntimeExecutions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).GetRuntimeExecutions(ctx, req.(*GetRuntimeExecutionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CollectorService_ServiceDesc is the grpc.ServiceDesc for CollectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "collector.CollectorService",
	HandlerType: (*CollectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRuntimeMetrics",
			Handler:    _CollectorService_GetRuntimeMetrics_Handler,
		},
		{
			MethodName: "GetRuntimeExecutions",
			Handler:    _CollectorService_GetRuntimeExecutions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "collector.proto",
}
