{
 "title": "Channel Runtime Resources",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   {
    "name": "testName",
    "label": "Test Name",
    "query": "from(bucket: \"benchmark-tests\")\r\n  |> range(start: -30d)  // Adjust range as needed\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"resources\")\r\n  |> keep(columns: [\"test_name\"])\r\n  |> distinct(column: \"test_name\")"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"benchmark-tests\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"resources\")\r\n  |> filter(fn: (r) => r[\"test_name\"] == \"${testName}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_milli_cores\")\r\n  |> keep(columns: [\"_value\", \"_time\"])\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 1000.0 })) \r\n  |> aggregateWindow(every: 1s, fn: mean)"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"benchmark-tests\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"resources\")\r\n  |> filter(fn: (r) => r[\"test_name\"] == \"${testName}\")  \r\n  |> filter(fn: (r) => r[\"_field\"] == \"memory_bytes\")\r\n  |> keep(columns: [\"_value\", \"_time\"])\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / (1024.0 * 1024.0) }))\r\n  |> aggregateWindow(every: 1s, fn: mean)"
    }
   ]
  },
  {
   "title": "Network RX",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"benchmark-tests\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"resources\")\r\n  |> filter(fn: (r) => r[\"test_name\"] == \"${testName}\")  \r\n  |> filter(fn: (r) => r[\"_field\"] == \"network_total_rx\")\r\n  |> keep(columns: [\"_value\", \"_time\"])\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / (1024.0 * 1024.0) }))\r\n  |> aggregateWindow(every: 1s, fn: mean)"
    }
   ]
  },
  {
   "title": "Network TX",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"benchmark-tests\")\r\n  |> range(start: ${__from:date}, stop: ${__to:date})\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"resources\")\r\n  |> filter(fn: (r) => r[\"test_name\"] == \"${testName}\")  \r\n  |> filter(fn: (r) => r[\"_field\"] == \"network_total_tx\")\r\n  |> keep(columns: [\"_value\", \"_time\"])\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / (1024.0 * 1024.0) }))\r\n  |> aggregateWindow(every: 1s, fn: mean)"
    }
   ]
  }
 ]
}