syntax = "proto3";

package devenv;

option go_package = ".";

service DevEnv {
    rpc Create(CreateRequest) returns (CreateResponse);
    rpc GetStatus(GetStatusRequest) returns (GetStatusResponse);
    rpc List(ListRequest) returns (ListResponse); 
    rpc Start(StartRequest) returns (StartResponse);
    rpc Stop(StopRequest) returns (StopResponse);
    rpc Delete(DeleteRequest) returns (DeleteResponse);
}

message CreateRequest {
    string name = 1;
    string type = 2;
    string region = 3;
    string spaceId = 4;
}

message CreateResponse {
    string environmentID = 1;
    string message = 2;
    bytes privateKey = 3;
    Error error = 4;
}

message GetStatusRequest {
    string region = 1;
    string environmentID = 2;
}

message GetStatusResponse {
    string status = 1;
    string message = 2;
    Error error = 3;
}

// Request message for listing all environments
message ListRequest {
    string region = 1;
}

// Response message for listing all environments
message ListResponse {
    repeated EnvironmentInfo environments = 1;
    Error error = 2;
}

// Information about an environment
message EnvironmentInfo {
    string environmentID = 1;
    string environmentName = 2;
    string region = 3;
    string status = 4;
}

message StartRequest {
    string region = 1;
    string environmentID = 2;
    string spaceId = 3;
}

message StartResponse {
    string message = 1;
    Error error = 2;
}

message StopRequest {
    string region = 1;
    string environmentID = 2;
    string spaceId = 3;
}

message StopResponse {
    string message = 1;
    Error error = 2;
}

message DeleteRequest {
    string region = 1;
    string environmentID = 2; 
    string spaceId = 3;
}

message DeleteResponse {
    string message = 1;
    Error error = 2;
}

message Error {
    string code = 1;
    string message = 2;
}