name: HTTP API Images Builder

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build_http-api.yaml'
      - 'libs/http/**'
      - 'services/http-api/**'
  pull_request:
    branches:
      - main
    paths:
      - 'github/workflows/build_http-api.yaml'
      - 'libs/http/**'
      - 'services/http-api/**'

jobs:
  build-images:
    runs-on: linux-arm64

    strategy:
      matrix:
        service: [http-api]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install # will run `yarn install` command

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.22'
        id: go

      - name: Generate Prisma Client
        run: yarn prisma generate

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}
          # Uncomment below to use for local workflow tests
          # username: ${{ secrets.GH_USERNAME }}
          # password: ${{ secrets.GHCR_PAT }}
      
      - name: Build HTTP API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: services/${{ matrix.service }}/deploy/Dockerfile
          platforms: linux/arm64
          push: false
          cache-from: type=registry,ref=ghcr.io/iotea-com/engine-${{ matrix.service }}:latest
          cache-to: type=inline
          build-args: |
            --build-arg GIT_BRANCH=${{ github.ref_name }}
            --build-arg GIT_COMMIT=${{ github.sha }}
            --build-arg GIT_DIRTY=false
            --build-arg BUILD_CREATOR=${{ github.actor }}